"""
Curated database of famous trekking expeditions with INR pricing and technical details.
"""

TREKS_DATA = [
    {
        "id": "kedarkantha",
        "name": "Kedarkantha Trek",
        "tagline": "The Queen of Winter Snow Summits",
        "region": "Uttarakhand",
        "country": "India",
        "duration_days": 6,
        "duration_text": "6 Days / 5 Nights",
        "distance_km": 20,
        "distance_text": "20 km",
        "max_altitude_ft": 12500,
        "max_altitude_text": "12,500 ft (3,810 m)",
        "difficulty": "Easy-Moderate",
        "difficulty_slug": "easy",
        "best_months": ["December", "January", "February", "March", "April"],
        "best_season": "Winter & Spring",
        "rating": 4.9,
        "reviews_count": 520,
        "price": "₹9,200",
        "image": "/static/img/kedarkantha_enhanced.jpg",
        "badge": "Top Winter Trek",
        "highlights": ["360° Himalayan Panorama", "Juda Ka Talab Lake", "Snow Peak Summit", "Dense Pine Forests"],
        "description": "Kedarkantha is India's most celebrated winter snow trek. Climbing to its peak at 12,500 ft treats you to a jaw-dropping 360-degree panorama of famous peaks including Swargarohini, Black Peak, and Bandarpoonch.",
        "fitness_level": "Beginner Friendly",
        "start_point": "Sankri, Uttarakhand",
        "itinerary": [
            {
                "day": 1,
                "title": "Drive from Dehradun to Sankri",
                "campsite": "Sankri Basecamp",
                "altitude": "6,400 ft (1,950 m)",
                "desc": "Scenic 210 km mountain drive alongside the Yamuna and Tons rivers to Sankri village."
            },
            {
                "day": 2,
                "title": "Trek from Sankri to Juda Ka Talab",
                "campsite": "Juda Ka Talab Campsite",
                "altitude": "9,100 ft (2,773 m)",
                "desc": "Trek through dense pine and oak forests to the frozen alpine lake of Juda Ka Talab."
            },
            {
                "day": 3,
                "title": "Trek from Juda Ka Talab to Kedarkantha Base",
                "campsite": "Kedarkantha Base Camp",
                "altitude": "11,250 ft (3,429 m)",
                "desc": "Climb out of tree line onto open snowy meadows with breathtaking views of the peak."
            },
            {
                "day": 4,
                "title": "Summit Day: Base Camp to Kedarkantha Summit & Descend to Hargaon",
                "campsite": "Hargaon Campsite",
                "altitude": "12,500 ft (3,810 m) Summit / 8,900 ft Camp",
                "desc": "Pre-dawn summit push to 12,500 ft for 360° sunrise panorama, then descend to Hargaon."
            },
            {
                "day": 5,
                "title": "Descend from Hargaon to Sankri",
                "campsite": "Sankri Village Guest House",
                "altitude": "6,400 ft (1,950 m)",
                "desc": "Gentle descent through golden pine forests and village apple orchards back to Sankri."
            },
            {
                "day": 6,
                "title": "Drive from Sankri back to Dehradun",
                "campsite": "Dehradun Railway Station / Airport",
                "altitude": "1,466 ft (447 m)",
                "desc": "Depart Sankri by morning vehicle, arriving in Dehradun by late evening."
            }
        ]
    },
    {
        "id": "everest-base-camp",
        "name": "Everest Base Camp (EBC)",
        "tagline": "The Legendary Footpath to the Roof of the World",
        "region": "Nepal Himalayas",
        "country": "Nepal",
        "duration_days": 14,
        "duration_text": "14 Days / 13 Nights",
        "distance_km": 130,
        "distance_text": "130 km",
        "max_altitude_ft": 17598,
        "max_altitude_text": "17,598 ft (5,364 m)",
        "difficulty": "Difficult",
        "difficulty_slug": "difficult",
        "best_months": ["March", "April", "May", "September", "October", "November"],
        "best_season": "Spring & Autumn",
        "rating": 5.0,
        "reviews_count": 1240,
        "price": "₹95,000",
        "image": "/static/img/trekking_mountain.jpg",
        "badge": "World Iconic",
        "highlights": ["Everest Base Camp & Kala Patthar", "Khumbu Icefall View", "Sherpa Culture in Namche", "Tengboche Monastery"],
        "description": "Standing beneath Mt. Everest (8,848m) is an unforgettable bucket-list achievement. Traverses through the heart of the Khumbu valley, ancient monasteries, suspension bridges, and Sherpa villages.",
        "fitness_level": "High Endurance Required",
        "start_point": "Lukla, Nepal",
        "itinerary": [
            {"day": 1, "title": "Fly Kathmandu to Lukla & Trek to Phakding", "campsite": "Phakding Lodge", "altitude": "8,563 ft (2,610 m)", "desc": "Thrilling mountain flight to Lukla followed by a scenic walk along Dudh Kosi river."},
            {"day": 2, "title": "Trek from Phakding to Namche Bazaar", "campsite": "Namche Bazaar Lodge", "altitude": "11,286 ft (3,440 m)", "desc": "Cross high Hillary suspension bridges and climb up to the bustling Sherpa capital."},
            {"day": 3, "title": "Acclimatization Day in Namche Bazaar", "campsite": "Namche Bazaar Lodge", "altitude": "12,730 ft (3,880 m) Everest View Hotel", "desc": "Hike to Everest View Hotel for first panorama of Everest, Lhotse, and Ama Dablam."},
            {"day": 4, "title": "Trek from Namche Bazaar to Tengboche", "campsite": "Tengboche Monastery Lodge", "altitude": "12,694 ft (3,870 m)", "desc": "Walk along rhododendron ridges to the famous Buddhist monastery of Tengboche."},
            {"day": 5, "title": "Trek from Tengboche to Dingboche", "campsite": "Dingboche Alpine Lodge", "altitude": "14,469 ft (4,410 m)", "desc": "Trail enters alpine tundra with stone-walled fields beneath the imposing Ama Dablam."},
            {"day": 6, "title": "Acclimatization Day: Hike to Nangkartshang Peak", "campsite": "Dingboche Alpine Lodge", "altitude": "16,732 ft (5,100 m) Peak View", "desc": "Climb ridge for stunning views of Makalu, Island Peak, and glaciers before resting."},
            {"day": 7, "title": "Trek from Dingboche to Lobuche", "campsite": "Lobuche Tea House", "altitude": "16,207 ft (4,940 m)", "desc": "Ascend past the Sherpa memorial chortens at Thokla Pass along Khumbu Glacier."},
            {"day": 8, "title": "Trek Lobuche to Gorak Shep & Everest Base Camp", "campsite": "Gorak Shep High Lodge", "altitude": "17,598 ft (5,364 m) EBC / 16,942 ft Camp", "desc": "Walk across moraines to Everest Base Camp touching the world-famous Khumbu icefall!"},
            {"day": 9, "title": "Sunrise at Kala Patthar & Descend to Pheriche", "campsite": "Pheriche Lodge", "altitude": "18,519 ft (5,644 m) Summit / 14,340 ft Camp", "desc": "Pre-dawn climb to Kala Patthar summit for closest direct view of Mount Everest."},
            {"day": 10, "title": "Trek from Pheriche back to Namche Bazaar", "campsite": "Namche Bazaar Lodge", "altitude": "11,286 ft (3,440 m)", "desc": "Fast descent through lush juniper forests and Tengboche back to Namche Bazaar."},
            {"day": 11, "title": "Trek from Namche Bazaar to Lukla", "campsite": "Lukla Tea House", "altitude": "9,318 ft (2,840 m)", "desc": "Final trail day crossing suspension bridges back to Lukla runway base."},
            {"day": 12, "title": "Fly from Lukla to Kathmandu", "campsite": "Kathmandu Hotel", "altitude": "4,593 ft (1,400 m)", "desc": "Scenic morning flight back to Kathmandu valley and celebration dinner."},
            {"day": 13, "title": "Buffer Day for Mountain Weather", "campsite": "Kathmandu Hotel", "altitude": "4,593 ft (1,400 m)", "desc": "Reserve day for flight delays or city exploration of UNESCO temples."},
            {"day": 14, "title": "Final Departure", "campsite": "Tribhuvan International Airport", "altitude": "4,593 ft (1,400 m)", "desc": "Transfer to airport with lifetime Himalayan memories."}
        ]
    },
    {
        "id": "kashmir-great-lakes",
        "name": "Kashmir Great Lakes Trek",
        "tagline": "Paradise on Earth with 7 High-Altitude Alpine Lakes",
        "region": "Jammu & Kashmir",
        "country": "India",
        "duration_days": 7,
        "duration_text": "7 Days / 6 Nights",
        "distance_km": 72,
        "distance_text": "72 km",
        "max_altitude_ft": 13800,
        "max_altitude_text": "13,800 ft (4,206 m)",
        "difficulty": "Moderate",
        "difficulty_slug": "moderate",
        "best_months": ["July", "August", "September"],
        "best_season": "Monsoon & Late Summer",
        "rating": 4.9,
        "reviews_count": 680,
        "price": "₹15,500",
        "image": "/static/img/himalayan_lake_trek.jpg",
        "badge": "Prettiest Alpine Trek",
        "highlights": ["7 Turquoise Alpine Lakes", "Gadsar Pass Crossing", "Lush Green Meadows (Bugyals)", "Floating Icebergs"],
        "description": "Widely acclaimed as the prettiest trek in India. Each day unveils a pristine emerald or turquoise lake tucked between jagged snow-clad mountains with vast wildflowers carpeting the valleys.",
        "fitness_level": "Moderate Fitness Required",
        "start_point": "Sonamarg, J&K",
        "itinerary": [
            {"day": 1, "title": "Drive from Srinagar to Sonamarg Basecamp", "campsite": "Shitkadi / Sonamarg Camp", "altitude": "7,780 ft (2,371 m)", "desc": "Drive past Sindh river valley and camp beside pine-covered mountain banks."},
            {"day": 2, "title": "Trek Sonamarg to Nichnai via Tabletop", "campsite": "Nichnai Campsite", "altitude": "11,500 ft (3,505 m)", "desc": "Ascend through maple and silver birch forests to the wide Nichnai valley."},
            {"day": 3, "title": "Trek Nichnai to Vishansar & Kishansar Lakes", "campsite": "Vishansar Lake Camp", "altitude": "12,011 ft (3,661 m)", "desc": "Cross Nichnai Pass (13,100 ft) into vast wildflower meadows and emerald lakes."},
            {"day": 4, "title": "Trek Vishansar to Gadsar via Gadsar Pass", "campsite": "Gadsar Lake Camp", "altitude": "13,800 ft (4,206 m) Pass / 10,700 ft Camp", "desc": "Highest pass crossover offering panoramic dual views of Vishansar and Kishansar."},
            {"day": 5, "title": "Trek Gadsar to Satsar (7 Lakes)", "campsite": "Satsar Valley Camp", "altitude": "12,000 ft (3,658 m)", "desc": "Walk along rolling emerald meadows to the cascade of seven interconnected lakes."},
            {"day": 6, "title": "Trek Satsar to Gangabal & Nundkol Lakes", "campsite": "Nundkol Lake Camp", "altitude": "11,500 ft (3,505 m)", "desc": "Cross Zaj Pass (13,400 ft) to camp under the towering glaciated face of Mt Harmukh."},
            {"day": 7, "title": "Descend Gangabal to Naranag & Drive to Srinagar", "campsite": "Srinagar Houseboat / Hotel", "altitude": "5,200 ft (1,585 m)", "desc": "Descend pine forests to historic Naranag temple ruins and drive to Srinagar."}
        ]
    },
    {
        "id": "hampta-pass",
        "name": "Hampta Pass Trek",
        "tagline": "Dramatic Valley Crossover from Kullu to Spiti",
        "region": "Himachal Pradesh",
        "country": "India",
        "duration_days": 5,
        "duration_text": "5 Days / 4 Nights",
        "distance_km": 35,
        "distance_text": "35 km",
        "max_altitude_ft": 14100,
        "max_altitude_text": "14,100 ft (4,297 m)",
        "difficulty": "Easy-Moderate",
        "difficulty_slug": "easy",
        "best_months": ["June", "July", "August", "September", "October"],
        "best_season": "Summer & Monsoon",
        "rating": 4.8,
        "reviews_count": 430,
        "price": "₹10,800",
        "image": "/static/img/trekking_mountain.jpg",
        "badge": "Best Dramatic Crossover",
        "highlights": ["Dramatic Landscape Shift", "Chandratal Moon Lake", "Shea Goru River Crossing", "Lush Kullu to Desert Spiti"],
        "description": "In just a few days, you cross from the lush green pine valleys of Kullu to the stark, rugged cold desert mountains of Spiti, culminating in the crescent moon waters of Chandratal Lake.",
        "fitness_level": "Beginner to Intermediate",
        "start_point": "Jobra / Manali, HP",
        "itinerary": [
            {"day": 1, "title": "Drive Manali to Jobra & Trek to Chika", "campsite": "Chika Campsite", "altitude": "10,100 ft (3,078 m)", "desc": "Drive to Jobra through 42 hairpin bends and trek along Rani river to Chika."},
            {"day": 2, "title": "Trek from Chika to Balu Ka Ghera", "campsite": "Balu Ka Ghera Camp", "altitude": "11,900 ft (3,627 m)", "desc": "Walk through boulder fields and alpine flower meadows to the sandy riverbed."},
            {"day": 3, "title": "Cross Hampta Pass & Descend to Shea Goru", "campsite": "Shea Goru Oasis Camp", "altitude": "14,100 ft (4,297 m) Pass / 12,900 ft Camp", "desc": "Climb steep snowfields to Hampta Pass and cross over into barren desert valley of Spiti."},
            {"day": 4, "title": "Trek Shea Goru to Chatru & Drive to Chandratal", "campsite": "Chandratal Moon Lake Camp", "altitude": "14,000 ft (4,267 m)", "desc": "River crossing at Shea Goru, descend to Chatru roadhead, and drive to crescent Chandratal Lake."},
            {"day": 5, "title": "Drive from Chandratal / Chatru back to Manali", "campsite": "Manali Mall Road", "altitude": "6,726 ft (2,050 m)", "desc": "Drive via Atal Tunnel or Rohtang Pass back to Manali by evening."}
        ]
    },
    {
        "id": "roopkund-trek",
        "name": "Roopkund Mystery Lake Trek",
        "tagline": "The High Altitude Glacial Skeleton Lake",
        "region": "Uttarakhand",
        "country": "India",
        "duration_days": 8,
        "duration_text": "8 Days / 7 Nights",
        "distance_km": 53,
        "distance_text": "53 km",
        "max_altitude_ft": 15696,
        "max_altitude_text": "15,696 ft (4,784 m)",
        "difficulty": "Difficult",
        "difficulty_slug": "difficult",
        "best_months": ["May", "June", "September", "October"],
        "best_season": "Summer & Autumn",
        "rating": 4.9,
        "reviews_count": 390,
        "price": "₹16,500",
        "image": "/static/img/winter_summit_trek.jpg",
        "badge": "Thrilling Expedition",
        "highlights": ["Ali & Bedni Bugyal Meadows", "Trisul & Nanda Ghunti Views", "Glacial Mystery Lake", "Junargali Ridge"],
        "description": "Roopkund is an enigmatic high-altitude glacial lake nestled deep in the Garhwal Himalayas. The trek traverses through Ali Bedni Bugyal, India's most expansive alpine meadow, straight to the feet of Mount Trisul.",
        "fitness_level": "Good Endurance Required",
        "start_point": "Lohajung, Uttarakhand",
        "itinerary": [
            {"day": 1, "title": "Drive Rishikesh / Kathgodam to Lohajung", "campsite": "Lohajung Basecamp", "altitude": "7,660 ft (2,335 m)", "desc": "210 km scenic mountain drive through Pauri and Tharali to basecamp village."},
            {"day": 2, "title": "Trek Lohajung to Didna Village", "campsite": "Didna Homestay Camp", "altitude": "8,045 ft (2,452 m)", "desc": "Descend to Neel Ganga river bridge and climb through oak forests to Didna."},
            {"day": 3, "title": "Trek Didna to Ali Bugyal & Bedni Bugyal", "campsite": "Bedni Bugyal Camp", "altitude": "11,540 ft (3,517 m)", "desc": "Climb out of tree line onto Asia's largest alpine meadow with Mt Trisul view."},
            {"day": 4, "title": "Acclimatization & Exploration at Bedni Bugyal", "campsite": "Bedni Bugyal Camp", "altitude": "11,540 ft (3,517 m)", "desc": "Acclimatization walks around Bedni Kund with breathtaking sunset on Nanda Ghunti."},
            {"day": 5, "title": "Trek Bedni Bugyal to Patar Nachauni", "campsite": "Patar Nachauni Camp", "altitude": "12,818 ft (3,907 m)", "desc": "Ascend past Ghora Lotani on a gradual exposed ridge path."},
            {"day": 6, "title": "Trek Patar Nachauni to Bhagwabasa", "campsite": "Bhagwabasa Stone Huts Camp", "altitude": "14,117 ft (4,303 m)", "desc": "Climb Kalu Vinayak temple ridge and enter barren, rocky glaciated terrain."},
            {"day": 7, "title": "Summit Push: Roopkund Lake & Junargali Ridge to Bedni", "campsite": "Bedni Bugyal Camp", "altitude": "15,696 ft (4,784 m) Lake / 11,540 ft Camp", "desc": "Early 4 AM climb on snow to the mystery skeletal lake and ridge, then descend to Bedni."},
            {"day": 8, "title": "Descend Bedni Bugyal to Wan & Drive to Lohajung", "campsite": "Lohajung Basecamp", "altitude": "7,660 ft (2,335 m)", "desc": "Descend through rhododendron forest to Wan village and jeep drive back to Lohajung."}
        ]
    },
    {
        "id": "annapurna-circuit",
        "name": "Annapurna Circuit Trek",
        "tagline": "Around the Mighty 8,000m Giants & Thorong La",
        "region": "Nepal Himalayas",
        "country": "Nepal",
        "duration_days": 12,
        "duration_text": "12 Days / 11 Nights",
        "distance_km": 160,
        "distance_text": "160 km",
        "max_altitude_ft": 17769,
        "max_altitude_text": "17,769 ft (5,416 m)",
        "difficulty": "Difficult",
        "difficulty_slug": "difficult",
        "best_months": ["March", "April", "May", "October", "November"],
        "best_season": "Spring & Autumn",
        "rating": 4.9,
        "reviews_count": 870,
        "price": "₹72,000",
        "image": "/static/img/himalayan_lake_trek.jpg",
        "badge": "Epic Global Trail",
        "highlights": ["Thorong La High Pass (5,416m)", "Muktinath Sacred Temple", "Tilicho Lake Option", "Diverse Microclimates"],
        "description": "Circumnavigating the Annapurna massif takes trekkers through subtropical river canyons, Tibetan plateaus, and over the thrilling Thorong La Pass with close-up views of Annapurna I and Dhaulagiri.",
        "fitness_level": "High Endurance Required",
        "start_point": "Besisahar, Nepal",
        "itinerary": [
            {"day": 1, "title": "Drive Kathmandu to Besisahar & Chame", "campsite": "Chame Teahouse", "altitude": "8,920 ft (2,710 m)", "desc": "Scenic 4WD drive through Marsyangdi river valley into Manang district."},
            {"day": 2, "title": "Trek Chame to Pisang", "campsite": "Upper Pisang Lodge", "altitude": "10,826 ft (3,300 m)", "desc": "Trail passes through dense apple orchards and curved rock wall of Paungda Danda."},
            {"day": 3, "title": "Trek Upper Pisang to Manang", "campsite": "Manang Village Lodge", "altitude": "11,614 ft (3,540 m)", "desc": "Upper trail via Ghyaru offers sweeping views of Annapurna II, III, and IV."},
            {"day": 4, "title": "Acclimatization Day in Manang", "campsite": "Manang Village Lodge", "altitude": "13,123 ft (4,000 m) Gangapurna View", "desc": "Visit Gangapurna glacier lake and ancient Buddhist monasteries."},
            {"day": 5, "title": "Trek Manang to Yak Kharka", "campsite": "Yak Kharka Lodge", "altitude": "13,484 ft (4,110 m)", "desc": "Gradual climb through scrub juniper pastures with grazing Himalayan yaks."},
            {"day": 6, "title": "Trek Yak Kharka to Thorong High Camp", "campsite": "Thorong High Camp", "altitude": "16,010 ft (4,880 m)", "desc": "Ascend scree slopes beneath the high pass to the base camp beneath Thorong Peak."},
            {"day": 7, "title": "Cross Thorong La Pass & Descend to Muktinath", "campsite": "Muktinath Sacred Lodge", "altitude": "17,769 ft (5,416 m) Pass / 12,467 ft Camp", "desc": "Conquer the legendary Thorong La pass at dawn and descend to sacred Muktinath temple."},
            {"day": 8, "title": "Trek Muktinath to Marpha via Kagbeni", "campsite": "Marpha Village Guest House", "altitude": "8,760 ft (2,670 m)", "desc": "Walk down Kali Gandaki gorge into the apple orchards and white stone streets of Marpha."},
            {"day": 9, "title": "Drive Marpha to Tatopani Hot Springs", "campsite": "Tatopani Springs Lodge", "altitude": "3,904 ft (1,190 m)", "desc": "Drive down deepest gorge in the world to natural therapeutic geothermal hot springs."},
            {"day": 10, "title": "Trek Tatopani to Ghorepani", "campsite": "Ghorepani Hilltop Lodge", "altitude": "9,350 ft (2,850 m)", "desc": "Climb through magnificent rhododendron forests to the sunrise viewpoint village."},
            {"day": 11, "title": "Sunrise at Poon Hill & Trek to Pokhara", "campsite": "Pokhara Lakeside Hotel", "altitude": "2,700 ft (822 m)", "desc": "Witness iconic Poon Hill sunrise over Dhaulagiri and Annapurna before driving to Pokhara."},
            {"day": 12, "title": "Drive Pokhara to Kathmandu", "campsite": "Kathmandu Hotel", "altitude": "4,593 ft (1,400 m)", "desc": "Return tourist bus or flight back to Kathmandu capital."}
        ]
    },
    {
        "id": "valley-of-flowers",
        "name": "Valley of Flowers & Hemkund Sahib",
        "tagline": "UNESCO World Heritage Botanical Wonder",
        "region": "Uttarakhand",
        "country": "India",
        "duration_days": 6,
        "duration_text": "6 Days / 5 Nights",
        "distance_km": 38,
        "distance_text": "38 km",
        "max_altitude_ft": 14200,
        "max_altitude_text": "14,200 ft (4,328 m)",
        "difficulty": "Easy-Moderate",
        "difficulty_slug": "easy",
        "best_months": ["July", "August", "September"],
        "best_season": "Monsoon Bloom",
        "rating": 4.8,
        "reviews_count": 490,
        "price": "₹10,200",
        "image": "/static/img/himalayan_lake_trek.jpg",
        "badge": "UNESCO Heritage",
        "highlights": ["650+ Endemic Wildflower Species", "Hemkund Sahib Glacial Lake", "Pushpawati River Valley", "Blue Poppies & Orchids"],
        "description": "A UNESCO World Heritage National Park transformed into a vibrant floral paradise during monsoon with hundreds of species of alpine flowers blooming along crystal streams against soaring glacier peaks.",
        "fitness_level": "Beginner to Intermediate",
        "start_point": "Govindghat, Uttarakhand",
        "itinerary": [
            {"day": 1, "title": "Drive Rishikesh / Haridwar to Govindghat", "campsite": "Govindghat Riverside Hotel", "altitude": "5,997 ft (1,828 m)", "desc": "Full day 270 km drive through the 5 holy river confluences (Panchprayag) of Alaknanda."},
            {"day": 2, "title": "Trek Govindghat to Ghangaria Basecamp", "campsite": "Ghangaria Basecamp", "altitude": "10,003 ft (3,049 m)", "desc": "13 km steady scenic trek beside Pushpawati river amidst misty Himalayan valleys."},
            {"day": 3, "title": "Trek Ghangaria to Valley of Flowers & Return", "campsite": "Ghangaria Basecamp", "altitude": "12,140 ft (3,700 m)", "desc": "Enter the UNESCO floral valley blanketed in 650+ species of blooming wild orchids and poppies."},
            {"day": 4, "title": "Trek Ghangaria to Hemkund Sahib Glacial Lake", "campsite": "Ghangaria Basecamp", "altitude": "14,200 ft (4,328 m)", "desc": "Climb stone steps to the sacred high-altitude Sikh gurudwara surrounded by 7 snow peaks."},
            {"day": 5, "title": "Trek Ghangaria to Govindghat & Drive to Badrinath", "campsite": "Badrinath / Joshimath Hotel", "altitude": "10,279 ft (3,133 m)", "desc": "Descend back to Govindghat and visit ancient Badrinath shrine and Mana border village."},
            {"day": 6, "title": "Drive Joshimath / Govindghat back to Rishikesh", "campsite": "Rishikesh Railway / Dehradun", "altitude": "1,120 ft (340 m)", "desc": "Morning departure down the Alaknanda river valley reaching Rishikesh by evening."}
        ]
    },
    {
        "id": "chadar-trek",
        "name": "Chadar Frozen River Trek",
        "tagline": "Walking on Ice in -30°C Zanskar Gorge",
        "region": "Ladakh",
        "country": "India",
        "duration_days": 8,
        "duration_text": "8 Days / 7 Nights",
        "distance_km": 62,
        "distance_text": "62 km",
        "max_altitude_ft": 11100,
        "max_altitude_text": "11,100 ft (3,383 m)",
        "difficulty": "Expert",
        "difficulty_slug": "expert",
        "best_months": ["January", "February"],
        "best_season": "Deep Winter (Sub-Zero)",
        "rating": 4.9,
        "reviews_count": 310,
        "price": "₹65,000",
        "image": "/static/img/winter_summit_trek.jpg",
        "badge": "Extreme Adventure",
        "highlights": ["Walking on Frozen Zanskar River", "Frozen Waterfalls", "Cave Camping", "-30°C Arctic Temperatures"],
        "description": "One of the most unique and extreme expeditions on Earth. Trekkers walk on the frozen blanket ('Chadar') of the wild Zanskar River flanked by towering vertical canyon walls in sub-zero Himalayan winter.",
        "fitness_level": "Extreme Mental & Physical Grit",
        "start_point": "Leh, Ladakh",
        "itinerary": [
            {"day": 1, "title": "Arrive in Leh & Acclimatize", "campsite": "Leh Heated Hotel", "altitude": "11,500 ft (3,505 m)", "desc": "Mandatory 48-hour sub-zero acclimatization in Leh with medical fitness check."},
            {"day": 2, "title": "Medical Checkup & Acclimatization in Leh", "campsite": "Leh Heated Hotel", "altitude": "11,500 ft (3,505 m)", "desc": "Visit Shanti Stupa, local Leh market, and complete mandatory government medical clearance."},
            {"day": 3, "title": "Drive Leh to Shingra Koma & Trek to Tsomo Paldar", "campsite": "Tsomo Paldar River Camp", "altitude": "10,400 ft (3,170 m)", "desc": "Step onto the glass-like frozen Zanskar river for the first ice walk to Tsomo."},
            {"day": 4, "title": "Trek Tsomo Paldar to Tibb Cave", "campsite": "Tibb Cave Camp", "altitude": "10,800 ft (3,292 m)", "desc": "Walk past surreal frozen waterfalls and towering vertical canyon walls."},
            {"day": 5, "title": "Trek Tibb Cave to Naerak Frozen Waterfall", "campsite": "Naerak Village Camp", "altitude": "11,100 ft (3,383 m)", "desc": "Reach the crown jewel of Chadar: the gigantic 50-foot frozen blue waterfall of Naerak."},
            {"day": 6, "title": "Trek Naerak back to Tibb Cave", "campsite": "Tibb Cave Camp", "altitude": "10,800 ft (3,292 m)", "desc": "Retrace footsteps on changing ice sheets with new crystal formations."},
            {"day": 7, "title": "Trek Tibb Cave to Shingra Koma & Drive to Leh", "campsite": "Leh Heated Hotel", "altitude": "11,500 ft (3,505 m)", "desc": "Final ice walk back to vehicle roadhead and warm dinner in Leh."},
            {"day": 8, "title": "Fly out from Leh", "campsite": "Kushok Bakula Rimpochee Airport", "altitude": "10,682 ft (3,256 m)", "desc": "Depart Leh with memories of surviving -30°C on the frozen river."}
        ]
    },
    {
        "id": "tour-du-mont-blanc",
        "name": "Tour du Mont Blanc (TMB)",
        "tagline": "The Ultimate 3-Country Alpine Odyssey",
        "region": "International (Alps)",
        "country": "France / Italy / Switzerland",
        "duration_days": 10,
        "duration_text": "10 Days / 9 Nights",
        "distance_km": 170,
        "distance_text": "170 km",
        "max_altitude_ft": 8743,
        "max_altitude_text": "8,743 ft (2,665 m)",
        "difficulty": "Moderate",
        "difficulty_slug": "moderate",
        "best_months": ["June", "July", "August", "September"],
        "best_season": "Alpine Summer",
        "rating": 4.9,
        "reviews_count": 940,
        "price": "₹1,20,000",
        "image": "/static/img/trekking_mountain.jpg",
        "badge": "European Masterpiece",
        "highlights": ["3 European Nations in 1 Trek", "Spectacular Mont Blanc Massif", "Gourmet Alpine Refuges", "Glacial Valleys"],
        "description": "Circumnavigates Western Europe's highest peak across France, Italy, and Switzerland. Offers world-class alpine vistas, delicious mountain refuge gastronomy, and charming historic villages.",
        "fitness_level": "Moderate to High",
        "start_point": "Les Houches / Chamonix, France",
        "itinerary": [
            {"day": 1, "title": "Les Houches to Refuge du Fioux (France)", "campsite": "Refuge du Fioux / Les Contamines", "altitude": "3,937 ft (1,200 m)", "desc": "Trek through pine woods and suspension bridge overlooking Bionnassay Glacier."},
            {"day": 2, "title": "Les Contamines to Refuge de la Croix du Bonhomme", "campsite": "Refuge de la Croix du Bonhomme", "altitude": "8,028 ft (2,447 m)", "desc": "Cross Roman road bridge and high Col du Bonhomme pass with expansive alpine vistas."},
            {"day": 3, "title": "Col de la Seigne Crossing into Italy to Courmayeur", "campsite": "Courmayeur Alpine Lodge (Italy)", "altitude": "4,015 ft (1,224 m)", "desc": "Step across French-Italian border at Col de la Seigne into Val Veny beneath limestone peaks."},
            {"day": 4, "title": "Courmayeur to Refuge Bonatti", "campsite": "Refugio Walter Bonatti", "altitude": "6,644 ft (2,025 m)", "desc": "Classic balcony trail across Val Ferret facing the dramatic Grandes Jorasses wall."},
            {"day": 5, "title": "Refuge Bonatti to La Fouly (Switzerland)", "campsite": "La Fouly Swiss Chalet (Switzerland)", "altitude": "5,250 ft (1,600 m)", "desc": "Cross the Grand Col Ferret into Switzerland through picturesque Valais meadows."},
            {"day": 6, "title": "La Fouly to Champex-Lac", "campsite": "Champex-Lac Lakeside Chalet", "altitude": "4,810 ft (1,466 m)", "desc": "Gentle woodland trail through quaint Swiss chalet villages and crystal blue lake."},
            {"day": 7, "title": "Champex-Lac to Trient via Bovine Route", "campsite": "Trient Alpine Refuge", "altitude": "4,265 ft (1,300 m)", "desc": "Traverse larch forests with views of Rhone valley to the pink church village of Trient."},
            {"day": 8, "title": "Trient to Tre-le-Champ (Back to France)", "campsite": "Tre-le-Champ Gite", "altitude": "4,649 ft (1,417 m)", "desc": "Cross Col de Balme back into France with panoramic view of Mont Blanc summit."},
            {"day": 9, "title": "Tre-le-Champ to Refuge La Flegere via Lac Blanc", "campsite": "Refuge La Flegere", "altitude": "6,158 ft (1,877 m)", "desc": "Ascend ladders and granite boulders to the reflective waters of Lac Blanc."},
            {"day": 10, "title": "La Flegere to Les Houches / Chamonix", "campsite": "Chamonix Center", "altitude": "3,396 ft (1,035 m)", "desc": "Balcony traverse past Le Brevent summit and descend back to Chamonix valley."}
        ]
    },
    {
        "id": "bali-pass",
        "name": "Bali Pass Trek",
        "tagline": "Thrilling High Altitude Crossover to Yamunotri",
        "region": "Uttarakhand",
        "country": "India",
        "duration_days": 8,
        "duration_text": "8 Days / 7 Nights",
        "distance_km": 66,
        "distance_text": "66 km",
        "max_altitude_ft": 16207,
        "max_altitude_text": "16,207 ft (4,940 m)",
        "difficulty": "Difficult",
        "difficulty_slug": "difficult",
        "best_months": ["May", "June", "September", "October"],
        "best_season": "Summer & Autumn",
        "rating": 4.9,
        "reviews_count": 280,
        "price": "₹22,500",
        "image": "/static/img/winter_summit_trek.jpg",
        "badge": "High Mountain Pass",
        "highlights": ["Ruinsara Alpine Lake", "Bali Pass Crossover (4,940m)", "Ancient Yamunotri Temple", "Swargarohini & Bandarpoonch Views"],
        "description": "An exhilarating high-altitude crossover trek connecting the Har Ki Dun valley to the holy shrine of Yamunotri across alpine ridges and dramatic knife-edge passes.",
        "fitness_level": "High Endurance Required",
        "start_point": "Sankri, Uttarakhand",
        "itinerary": [
            {"day": 1, "title": "Drive Dehradun to Sankri", "campsite": "Sankri Basecamp", "altitude": "6,400 ft (1,950 m)", "desc": "Mountain drive along Tons river."},
            {"day": 2, "title": "Trek Sankri to Seema via Taluka", "campsite": "Seema Campsite", "altitude": "8,500 ft (2,590 m)", "desc": "Follow Supin river gorge through walnut and chestnut woods."},
            {"day": 3, "title": "Trek Seema to Rainbasera", "campsite": "Rainbasera Camp", "altitude": "10,200 ft (3,109 m)", "desc": "Ascend into Ruinsara river valley with tumbling waterfalls."},
            {"day": 4, "title": "Trek Rainbasera to Ruinsara Tal", "campsite": "Ruinsara Tal Camp", "altitude": "11,800 ft (3,597 m)", "desc": "Camp beside the sacred emerald waters of Ruinsara glacial lake."},
            {"day": 5, "title": "Trek Ruinsara Tal to Odari", "campsite": "Odari Basecamp", "altitude": "13,100 ft (3,993 m)", "desc": "Climb up to high moraine camp with views of Swargarohini."},
            {"day": 6, "title": "Cross Bali Pass & Descend to Upper Damini", "campsite": "Damini High Camp", "altitude": "16,207 ft (4,940 m) Pass / 13,400 ft Camp", "desc": "Conquer the razor-edge Bali Pass ridge and descend steep snowfields."},
            {"day": 7, "title": "Trek Damini to Yamunotri & Janki Chatti", "campsite": "Janki Chatti Hotel", "altitude": "8,700 ft (2,652 m)", "desc": "Visit ancient Yamunotri shrine hot springs and reach Janki Chatti."},
            {"day": 8, "title": "Drive Janki Chatti to Dehradun", "campsite": "Dehradun Terminal", "altitude": "1,466 ft (447 m)", "desc": "Return drive through Mussoorie."}
        ]
    },
    {
        "id": "kuari-pass",
        "name": "Kuari Pass Trek",
        "tagline": "The Famous Lord Curzon Trail facing Nanda Devi",
        "region": "Uttarakhand",
        "country": "India",
        "duration_days": 6,
        "duration_text": "6 Days / 5 Nights",
        "distance_km": 33,
        "distance_text": "33 km",
        "max_altitude_ft": 12516,
        "max_altitude_text": "12,516 ft (3,815 m)",
        "difficulty": "Easy-Moderate",
        "difficulty_slug": "easy",
        "best_months": ["November", "December", "January", "February", "March", "April"],
        "best_season": "Winter Snow Trail",
        "rating": 4.8,
        "reviews_count": 510,
        "price": "₹9,800",
        "image": "/static/img/winter_summit_trek.jpg",
        "badge": "Lord Curzon Trail",
        "highlights": ["Front-row view of Mt Nanda Devi", "Gorson Bugyal Snow Meadows", "Auli Ski Slopes", "Pristine Oak Forests"],
        "description": "Walk in the footsteps of Lord Curzon on this legendary trail granting the most spectacular and direct views of India's second-highest summit, Mt. Nanda Devi (7,816m), along with Kamet and Dronagiri.",
        "fitness_level": "Beginner Friendly",
        "start_point": "Joshimath, Uttarakhand",
        "itinerary": [
            {"day": 1, "title": "Drive Rishikesh to Joshimath", "campsite": "Joshimath Hotel", "altitude": "6,150 ft (1,875 m)", "desc": "Scenic drive along the confluence of the Alaknanda and Mandakini rivers."},
            {"day": 2, "title": "Drive to Dhak & Trek to Gulling Top", "campsite": "Gulling Top Campsite", "altitude": "9,600 ft (2,926 m)", "desc": "Trek through picturesque mountain villages and terraced farms."},
            {"day": 3, "title": "Trek Gulling Top to Tali Forest Camp", "campsite": "Tali Forest Camp", "altitude": "11,070 ft (3,374 m)", "desc": "Dense rhododendron and silver fir woods opening to Dronagiri peak views."},
            {"day": 4, "title": "Summit Day: Tali to Kuari Pass & Back", "campsite": "Tali Forest Camp", "altitude": "12,516 ft (3,815 m) Pass / 11,070 ft Camp", "desc": "Climb up to the windswept pass with glorious 360° panoramas of Nanda Devi, Kamet, and Trishul."},
            {"day": 5, "title": "Trek Tali to Auli via Gorson Bugyal & Drive to Joshimath", "campsite": "Joshimath Hotel", "altitude": "6,150 ft (1,875 m)", "desc": "Traverse the vast snow-carpeted meadows of Gorson Bugyal down to Auli ski resort."},
            {"day": 6, "title": "Drive Joshimath to Rishikesh", "campsite": "Rishikesh Railway / Dehradun", "altitude": "1,120 ft (340 m)", "desc": "Return drive to Rishikesh by evening."}
        ]
    },
    {
        "id": "brahmatal-trek",
        "name": "Brahmatal Trek",
        "tagline": "The Winter Wonderland with Grand Views of Mt. Trishul",
        "region": "Uttarakhand",
        "country": "India",
        "duration_days": 6,
        "duration_text": "6 Days / 5 Nights",
        "distance_km": 24,
        "distance_text": "24 km",
        "max_altitude_ft": 12250,
        "max_altitude_text": "12,250 ft (3,734 m)",
        "difficulty": "Easy-Moderate",
        "difficulty_slug": "easy",
        "best_months": ["December", "January", "February", "March"],
        "best_season": "Winter Snow",
        "rating": 4.9,
        "reviews_count": 640,
        "price": "₹9,800",
        "image": "/static/img/winter_summit_trek.jpg",
        "badge": "Top Winter Ridge",
        "highlights": ["Frozen Brahmatal & Bekaltal Lakes", "Face-to-Face View of Mt Trishul (7,120m)", "Nanda Ghunti Panorama", "Snow-laden Oak Forests"],
        "description": "Brahmatal is one of the rare winter treks in the Himalayas that takes you along grand snow-covered ridges with direct, towering views of Mt. Trishul and Nanda Ghunti reflecting on high glacial lakes.",
        "fitness_level": "Beginner Friendly",
        "start_point": "Lohajung, Uttarakhand",
        "itinerary": [
            {"day": 1, "title": "Drive Kathgodam to Lohajung", "campsite": "Lohajung Guest House", "altitude": "7,600 ft (2,316 m)", "desc": "Scenic drive along Kumaon valleys and pine hills."},
            {"day": 2, "title": "Trek Lohajung to Bekaltal", "campsite": "Bekaltal Campsite", "altitude": "9,689 ft (2,953 m)", "desc": "Trek through dense oak and rhododendron forests to the serene lake of Bekaltal."},
            {"day": 3, "title": "Trek Bekaltal to Brahmatal", "campsite": "Brahmatal Campsite", "altitude": "10,440 ft (3,182 m)", "desc": "Ascend above tree line to panoramic snowfields and the sacred Brahmatal lake."},
            {"day": 4, "title": "Summit Day: Brahmatal to Brahmatal Pass & Khorurai", "campsite": "Khorurai Campsite", "altitude": "12,250 ft (3,734 m) Top / 9,160 ft Camp", "desc": "Summit push to Brahmatal Top offering dramatic close-up vistas of Mt. Trishul."},
            {"day": 5, "title": "Trek Khorurai to Lohajung", "campsite": "Lohajung Basecamp", "altitude": "7,600 ft (2,316 m)", "desc": "Descend via forest trails back to base village Lohajung."},
            {"day": 6, "title": "Drive Lohajung to Kathgodam", "campsite": "Kathgodam Railway Station", "altitude": "1,800 ft (548 m)", "desc": "Return journey to Kathgodam by evening."}
        ]
    },
    {
        "id": "goechala-trek",
        "name": "Goechala Trek",
        "tagline": "Grand Front-Row Panorama of Mt. Kanchenjunga",
        "region": "Sikkim",
        "country": "India",
        "duration_days": 10,
        "duration_text": "10 Days / 9 Nights",
        "distance_km": 90,
        "distance_text": "90 km",
        "max_altitude_ft": 15100,
        "max_altitude_text": "15,100 ft (4,602 m)",
        "difficulty": "Difficult",
        "difficulty_slug": "difficult",
        "best_months": ["April", "May", "October", "November"],
        "best_season": "Spring & Autumn",
        "rating": 4.9,
        "reviews_count": 480,
        "price": "₹21,500",
        "image": "/static/img/mountain_hero.jpg",
        "badge": "Kanchenjunga Vista",
        "highlights": ["Sunrise on Mt. Kanchenjunga (8,586m)", "Samiti Glacial Lake", "Dzongri Top Sunrise Point", "Blooming Rhododendron Sanctuaries"],
        "description": "Goechala is the crown jewel trek of Sikkim, leading through the Kanchenjunga Biosphere Reserve right up to the base of the world's 3rd highest peak, Mt. Kanchenjunga.",
        "fitness_level": "High Endurance Required",
        "start_point": "Yuksom, Sikkim",
        "itinerary": [
            {"day": 1, "title": "Drive NJP / Bagdogra to Yuksom", "campsite": "Yuksom Heritage Lodge", "altitude": "5,800 ft (1,768 m)", "desc": "Drive through Teesta river valleys to the historic first capital of Sikkim."},
            {"day": 2, "title": "Trek Yuksom to Sachen", "campsite": "Sachen Camp", "altitude": "7,200 ft (2,195 m)", "desc": "Hike through lush subtropical rainforests with cascading suspension bridges."},
            {"day": 3, "title": "Trek Sachen to Tshoka", "campsite": "Tshoka Tibetan Camp", "altitude": "9,650 ft (2,941 m)", "desc": "Steep climb past Bakhim village into misty rhododendron forests."},
            {"day": 4, "title": "Trek Tshoka to Dzongri", "campsite": "Dzongri High Meadow", "altitude": "12,980 ft (3,956 m)", "desc": "Ascend the famous Phedang ridge into subalpine meadows."},
            {"day": 5, "title": "Sunrise at Dzongri Top & Trek to Thansing", "campsite": "Thansing Campsite", "altitude": "13,680 ft (4,170 m)", "desc": "Golden sunrise on 16 Himalayan peaks from Dzongri Top, then descend to Prek Chu river valley."},
            {"day": 6, "title": "Trek Thansing to Lamuney", "campsite": "Lamuney Basecamp", "altitude": "13,700 ft (4,176 m)", "desc": "Gentle alpine walk past the sacred emerald waters of Samiti Lake."},
            {"day": 7, "title": "Summit Day: Lamuney to Goechala View Point 1 & Back to Kokchurang", "campsite": "Kokchurang Camp", "altitude": "15,100 ft (4,602 m) Pass / 12,000 ft Camp", "desc": "Early 3 AM ascent to Goechala View Point 1 for the unmatched sunrise illuminating Kanchenjunga's colossal South Face."},
            {"day": 8, "title": "Trek Kokchurang to Tshoka", "campsite": "Tshoka Campsite", "altitude": "9,650 ft (2,941 m)", "desc": "Scenic direct ridge trail via Phedang."},
            {"day": 9, "title": "Trek Tshoka to Yuksom", "campsite": "Yuksom Lodge", "altitude": "5,800 ft (1,768 m)", "desc": "Descent through dense woods back to Yuksom."},
            {"day": 10, "title": "Drive Yuksom to NJP / Bagdogra", "campsite": "Siliguri / NJP Terminal", "altitude": "400 ft (122 m)", "desc": "Depart with unforgettable memories of Kanchenjunga."}
        ]
    },
    {
        "id": "har-ki-dun",
        "name": "Har Ki Dun Trek",
        "tagline": "The Valley of Gods & Ancient Himalayan Legends",
        "region": "Uttarakhand",
        "country": "India",
        "duration_days": 7,
        "duration_text": "7 Days / 6 Nights",
        "distance_km": 47,
        "distance_text": "47 km",
        "max_altitude_ft": 11700,
        "max_altitude_text": "11,700 ft (3,566 m)",
        "difficulty": "Moderate",
        "difficulty_slug": "moderate",
        "best_months": ["April", "May", "June", "September", "October", "November", "December"],
        "best_season": "Spring, Autumn & Winter",
        "rating": 4.8,
        "reviews_count": 590,
        "price": "₹10,500",
        "image": "/static/img/trekking_mountain.jpg",
        "badge": "Mythological Valley",
        "highlights": ["Cradle-shaped amphitheater valley", "Views of Mt. Swargarohini", "Ancient 3,000-year-old wooden village of Osla", "Jaundhar Glacier Excursion"],
        "description": "Har Ki Dun (Valley of Gods) is steeped in Mahabharata mythology as the pathway taken by the Pandavas to ascend to heaven. Features pristine river valleys, ancient carved wooden temples, and alpine flower gardens.",
        "fitness_level": "Moderate Fitness",
        "start_point": "Sankri, Uttarakhand",
        "itinerary": [
            {"day": 1, "title": "Drive Dehradun to Sankri", "campsite": "Sankri Guest House", "altitude": "6,400 ft (1,950 m)", "desc": "Mountain drive along Tons river gorge."},
            {"day": 2, "title": "Drive Sankri to Taluka & Trek to Pauni Garaat", "campsite": "Pauni Garaat Camp", "altitude": "8,200 ft (2,500 m)", "desc": "Trek alongside the roaring Supin river under towering deodar trees."},
            {"day": 3, "title": "Trek Pauni Garaat to Kalkattiyadhar", "campsite": "Kalkattiyadhar Camp", "altitude": "9,800 ft (2,987 m)", "desc": "Pass through the ancient timber village of Osla with its historic Someshwar temple."},
            {"day": 4, "title": "Trek Kalkattiyadhar to Har Ki Dun Valley & Jaundhar Glacier View", "campsite": "Har Ki Dun Camp", "altitude": "11,700 ft (3,566 m)", "desc": "Enter the majestic cradle-shaped valley dominated by the sheer face of Swargarohini I & II."},
            {"day": 5, "title": "Trek Har Ki Dun to Pauni Garaat", "campsite": "Pauni Garaat Camp", "altitude": "8,200 ft (2,500 m)", "desc": "Leisurely descent enjoying the changing views of the Tons basin."},
            {"day": 6, "title": "Trek Pauni Garaat to Taluka & Drive to Sankri", "campsite": "Sankri Village Guest House", "altitude": "6,400 ft (1,950 m)", "desc": "Finish the trail at Taluka and return to Sankri."},
            {"day": 7, "title": "Drive Sankri to Dehradun", "campsite": "Dehradun Terminal", "altitude": "1,466 ft (447 m)", "desc": "Arrive in Dehradun by late afternoon."}
        ]
    },
    {
        "id": "pin-parvati-pass",
        "name": "Pin Parvati Pass Trek",
        "tagline": "The Grand Trans-Himalayan Crossover Expedition",
        "region": "Himachal Pradesh",
        "country": "India",
        "duration_days": 11,
        "duration_text": "11 Days / 10 Nights",
        "distance_km": 110,
        "distance_text": "110 km",
        "max_altitude_ft": 17450,
        "max_altitude_text": "17,450 ft (5,319 m)",
        "difficulty": "Expert",
        "difficulty_slug": "expert",
        "best_months": ["July", "August", "September"],
        "best_season": "Monsoon & Early Autumn",
        "rating": 5.0,
        "reviews_count": 310,
        "price": "₹38,000",
        "image": "/static/img/mountain_hero.jpg",
        "badge": "Ultimate Trans-Himalaya",
        "highlights": ["Lush Parvati Valley to Cold Desert Spiti", "Mantalai Sacred Glacial Lake", "Technical Glacial Pass Crossover (5,319m)", "Mud Village in Spiti"],
        "description": "Considered India's most formidable trekking challenge, Pin Parvati crosses from the rainforests and hot springs of Parvati Valley over a heavily glaciated pass into the barren lunar desert of Spiti Valley.",
        "fitness_level": "Expert Mountaineer Fitness",
        "start_point": "Barsheni / Kasol, Himachal Pradesh",
        "itinerary": [
            {"day": 1, "title": "Drive Manali to Barsheni & Trek to Kheerganga", "campsite": "Kheerganga Hot Springs", "altitude": "9,700 ft (2,956 m)", "desc": "Begin trek in Parvati valley and enjoy natural hot sulfur springs."},
            {"day": 2, "title": "Trek Kheerganga to Tunda Bhuj", "campsite": "Tunda Bhuj Camp", "altitude": "10,800 ft (3,292 m)", "desc": "Cross wooden bridges over rushing gorges and birch groves."},
            {"day": 3, "title": "Trek Tunda Bhuj to Thakur Kuan", "campsite": "Thakur Kuan Camp", "altitude": "11,800 ft (3,597 m)", "desc": "Navigate giant boulder sections and river pulley crossings."},
            {"day": 4, "title": "Trek Thakur Kuan to Odi Thach", "campsite": "Odi Thach Meadow", "altitude": "12,800 ft (3,901 m)", "desc": "Hike across wide braided glacial flats and wildflower pastures."},
            {"day": 5, "title": "Trek Odi Thach to Mantalai Lake", "campsite": "Mantalai Glacial Camp", "altitude": "13,400 ft (4,084 m)", "desc": "Reach the sacred source of the Parvati River at the turquoise Mantalai Lake."},
            {"day": 6, "title": "Trek Mantalai to Parvati Side Base Camp", "campsite": "High Base Camp", "altitude": "15,100 ft (4,602 m)", "desc": "Steep scree and moraine climb towards the glacier snout."},
            {"day": 7, "title": "Summit Day: Cross Pin Parvati Pass to Pin Side Base Camp", "campsite": "Pin Glacier Base Camp", "altitude": "17,450 ft (5,319 m) Pass / 14,800 ft Camp", "desc": "Traverse crevassed snowfields to conquer Pin Parvati Pass into Spiti Valley."},
            {"day": 8, "title": "Trek Pin Base to Tiya", "campsite": "Tiya Camp", "altitude": "13,100 ft (3,993 m)", "desc": "Descend along the striking purple and rust-red cliffs of Pin River."},
            {"day": 9, "title": "Trek Tiya to Mud Village & Drive to Kaza", "campsite": "Kaza Homestay / Hotel", "altitude": "12,470 ft (3,800 m)", "desc": "Reach the historic fortress village of Mud in Spiti and drive to Kaza."},
            {"day": 10, "title": "Drive Kaza to Manali via Kunzum Pass & Rohtang Tunnel", "campsite": "Manali Hotel", "altitude": "6,725 ft (2,050 m)", "desc": "Epic scenic drive crossing high Himalayan passes back to Kullu valley."},
            {"day": 11, "title": "Depart from Manali", "campsite": "Manali Bus Stand", "altitude": "6,725 ft (2,050 m)", "desc": "Expedition concludes with celebration."}
        ]
    },
    {
        "id": "tarsar-marsar",
        "name": "Tarsar Marsar Trek",
        "tagline": "The Royal Twin Alpine Lakes of Kashmir",
        "region": "Jammu & Kashmir",
        "country": "India",
        "duration_days": 7,
        "duration_text": "7 Days / 6 Nights",
        "distance_km": 48,
        "distance_text": "48 km",
        "max_altitude_ft": 13201,
        "max_altitude_text": "13,201 ft (4,024 m)",
        "difficulty": "Moderate",
        "difficulty_slug": "moderate",
        "best_months": ["July", "August", "September"],
        "best_season": "Summer Alpine",
        "rating": 4.9,
        "reviews_count": 530,
        "price": "₹14,800",
        "image": "/static/img/himalayan_lake_trek.jpg",
        "badge": "Kashmir Paradise",
        "highlights": ["Camping directly beside Tarsar Lake", "Almond-shaped blue waters of Sundersar & Marsar", "Velvet meadows of Lidderwat Valley", "Gujjar shepherd settlements"],
        "description": "Tarsar Marsar is celebrated for offering the privilege of pitching your tents right on the shore of the royal almond-shaped Tarsar lake, surrounded by snow-draped alpine cirques in Kashmir.",
        "fitness_level": "Moderate Fitness",
        "start_point": "Aru Valley, Pahalgam, Kashmir",
        "itinerary": [
            {"day": 1, "title": "Drive Srinagar to Aru Valley", "campsite": "Aru Valley Riverside Camp", "altitude": "7,958 ft (2,426 m)", "desc": "Scenic drive through saffron fields of Pampore and apple orchards of Pahalgam to Aru."},
            {"day": 2, "title": "Trek Aru Valley to Lidderwat", "campsite": "Lidderwat Meadow Camp", "altitude": "9,131 ft (2,783 m)", "desc": "Follow the Lidder river through pine forests and sprawling Gujjar pastoral meadows."},
            {"day": 3, "title": "Trek Lidderwat to Shekwas", "campsite": "Shekwas Campsite", "altitude": "11,039 ft (3,365 m)", "desc": "Gentle climb along Kolahoi river tributaries into wide rolling high valleys."},
            {"day": 4, "title": "Trek Shekwas to Tarsar Lake", "campsite": "Tarsar Lake Shore Camp", "altitude": "12,449 ft (3,794 m)", "desc": "Climb over alpine ridges to behold the majestic turquoise waters of Tarsar Lake."},
            {"day": 5, "title": "Tarsar Pass Crossing to Sundersar Lake & Marsar View", "campsite": "Sundersar High Camp", "altitude": "13,201 ft (4,024 m) Pass / 12,946 ft Camp", "desc": "Cross the high Tarsar Pass to Sundersar Lake and look down into the mystical Marsar lake."},
            {"day": 6, "title": "Trek Sundersar to Homwas via Jagmargi", "campsite": "Homwas Campsite", "altitude": "11,500 ft (3,505 m)", "desc": "Descend through the golden alpine meadows of Jagmargi."},
            {"day": 7, "title": "Trek Homwas to Aru & Drive back to Srinagar", "campsite": "Srinagar Dal Lake", "altitude": "5,200 ft (1,585 m)", "desc": "Complete the loop to Aru and drive to Srinagar by evening."}
        ]
    },
    {
        "id": "rupin-pass",
        "name": "Rupin Pass Trek",
        "tagline": "India's Most Dramatic Waterfall & Crossover Ridge",
        "region": "Uttarakhand",
        "country": "India",
        "duration_days": 8,
        "duration_text": "8 Days / 7 Nights",
        "distance_km": 52,
        "distance_text": "52 km",
        "max_altitude_ft": 15250,
        "max_altitude_text": "15,250 ft (4,650 m)",
        "difficulty": "Difficult",
        "difficulty_slug": "difficult",
        "best_months": ["May", "June", "September", "October"],
        "best_season": "Summer & Autumn",
        "rating": 4.9,
        "reviews_count": 680,
        "price": "₹16,500",
        "image": "/static/img/trekking_mountain.jpg",
        "badge": "Spectacular Crossover",
        "highlights": ["Three-stage Rupin Waterfall climb", "Jhaka hanging village", "Snow gully climb to Rupin Pass (4,650m)", "Sangla Valley apple orchards"],
        "description": "Rupin Pass is legendary for its ever-changing scenery: starting from the dense forests of Uttarakhand, climbing right alongside a monumental three-tier waterfall, conquering a dramatic snow gully, and emerging into the fairytale valley of Kinnaur, Himachal.",
        "fitness_level": "High Endurance Required",
        "start_point": "Dhaula, Uttarakhand",
        "itinerary": [
            {"day": 1, "title": "Drive Dehradun to Dhaula", "campsite": "Dhaula Base Camp", "altitude": "5,100 ft (1,554 m)", "desc": "Mountain drive along Tons river."},
            {"day": 2, "title": "Trek Dhaula to Sewa", "campsite": "Sewa Village Homestay", "altitude": "6,300 ft (1,920 m)", "desc": "Walk past apple orchards and terraced fields to the iconic Kinnauri-style temple in Sewa."},
            {"day": 3, "title": "Trek Sewa to Jhaka (Hanging Village)", "campsite": "Jhaka Village Camp", "altitude": "8,700 ft (2,652 m)", "desc": "Cross the border into Himachal and climb the steep stone trail to Jhaka village clinging to the cliffside."},
            {"day": 4, "title": "Trek Jhaka to Saruwas Thach", "campsite": "Saruwas Thach Camp", "altitude": "10,250 ft (3,124 m)", "desc": "Enter the Rupin river gorge with snow bridges and birch forests."},
            {"day": 5, "title": "Trek Saruwas Thach to Dhanderas Thach (Lower Waterfall)", "campsite": "Lower Waterfall Camp", "altitude": "11,680 ft (3,560 m)", "desc": "Unmatched view of the colossal multi-tiered Rupin waterfall tumbling thousands of feet."},
            {"day": 6, "title": "Acclimatize & Climb to Upper Waterfall Camp", "campsite": "Upper Waterfall Camp", "altitude": "13,120 ft (4,000 m)", "desc": "Climb directly up the rocky flank of the waterfall into the high glacial amphitheater."},
            {"day": 7, "title": "Summit Day: Cross Rupin Pass to Ronti Gad", "campsite": "Ronti Gad Campsite", "altitude": "15,250 ft (4,650 m) Pass / 13,000 ft Camp", "desc": "Climb the steep snow gully to Rupin Pass for 360° views of the Kinnaur Kailash range, then slide down snowfields."},
            {"day": 8, "title": "Trek Ronti Gad to Sangla & Drive to Shimla", "campsite": "Shimla / Chandigarh", "altitude": "7,200 ft (2,195 m)", "desc": "Descend to Sangla village in Kinnaur and depart for Shimla."}
        ]
    },
    {
        "id": "markha-valley",
        "name": "Markha Valley Trek",
        "tagline": "The Classic Silk Route Canyon & High Plateau of Ladakh",
        "region": "Ladakh",
        "country": "India",
        "duration_days": 8,
        "duration_text": "8 Days / 7 Nights",
        "distance_km": 65,
        "distance_text": "65 km",
        "max_altitude_ft": 17060,
        "max_altitude_text": "17,060 ft (5,200 m)",
        "difficulty": "Difficult",
        "difficulty_slug": "difficult",
        "best_months": ["June", "July", "August", "September"],
        "best_season": "Ladakh Summer",
        "rating": 4.8,
        "reviews_count": 420,
        "price": "₹18,500",
        "image": "/static/img/mountain_hero.jpg",
        "badge": "Ladakh Classic",
        "highlights": ["Hemis National Park & Snow Leopard Habitat", "Kongmaru La Pass (5,200m)", "Kang Yatse Peak Views (6,400m)", "Ancient Tibetan Chortens and Monasteries"],
        "description": "The Markha Valley trek is the quintessential Ladakh expedition. Follows canyon rivers, traverses high green oases, passes ruined hilltop forts, and ascends over Kongmaru La pass facing the Karakoram ranges.",
        "fitness_level": "Good High Altitude Endurance",
        "start_point": "Leh, Ladakh",
        "itinerary": [
            {"day": 1, "title": "Acclimatization in Leh", "campsite": "Leh Boutique Hotel", "altitude": "11,500 ft (3,505 m)", "desc": "Rest day to acclimatize to high altitude, visit Leh Palace and Shanti Stupa."},
            {"day": 2, "title": "Drive Leh to Chilling & Trek to Skiu", "campsite": "Skiu Village Camp", "altitude": "11,150 ft (3,398 m)", "desc": "Cross the Zanskar river via cable bridge and hike along the Markha stream."},
            {"day": 3, "title": "Trek Skiu to Sara", "campsite": "Sara Campsite", "altitude": "11,800 ft (3,597 m)", "desc": "Gentle walk through the willow-lined canyon floor."},
            {"day": 4, "title": "Trek Sara to Markha Village", "campsite": "Markha Homestay / Camp", "altitude": "12,460 ft (3,798 m)", "desc": "Reach the largest settlement with ancient monastery and fort ruins."},
            {"day": 5, "title": "Trek Markha to Thachungtse", "campsite": "Thachungtse Camp", "altitude": "13,940 ft (4,249 m)", "desc": "Pass Hankar village and look up at the towering pyramid of Mt. Kang Yatse."},
            {"day": 6, "title": "Trek Thachungtse to Nimaling Plateau", "campsite": "Nimaling High Plateau", "altitude": "15,580 ft (4,749 m)", "desc": "Ascend to the vast high-altitude pasture where nomads graze their yaks."},
            {"day": 7, "title": "Cross Kongmaru La Pass & Descend to Chokdo & Drive to Leh", "campsite": "Leh Hotel", "altitude": "17,060 ft (5,200 m) Pass / 11,500 ft Leh", "desc": "Conquer Kongmaru La with views of Karakoram and K2 in the far horizon, then descend through Shang gorge."},
            {"day": 8, "title": "Depart Leh Airport", "campsite": "Leh Kushok Bakula Airport", "altitude": "10,682 ft (3,256 m)", "desc": "Flight back over the snow-covered Himalayas."}
        ]
    },
    {
        "id": "bhrigu-lake",
        "name": "Bhrigu Lake Trek",
        "tagline": "The Sacred Color-Changing Alpine Pool of Manali",
        "region": "Himachal Pradesh",
        "country": "India",
        "duration_days": 4,
        "duration_text": "4 Days / 3 Nights",
        "distance_km": 25,
        "distance_text": "25 km",
        "max_altitude_ft": 14100,
        "max_altitude_text": "14,100 ft (4,298 m)",
        "difficulty": "Easy-Moderate",
        "difficulty_slug": "easy",
        "best_months": ["May", "June", "July", "August", "September", "October"],
        "best_season": "Summer & Autumn",
        "rating": 4.7,
        "reviews_count": 610,
        "price": "₹6,500",
        "image": "/static/img/himalayan_lake_trek.jpg",
        "badge": "Weekend Glacial Lake",
        "highlights": ["Sacred Bhrigu Lake at 14,100 ft", "Rola Kholi Velvet Alpine Grasslands", "Pir Panjal & Dhauladhar Mountain Ranges", "Easy access from Manali"],
        "description": "Bhrigu Lake is one of the few high alpine treks that takes you from 6,000 ft directly into rolling alpine grasslands above 14,000 ft in just a few days, leading to the sacred pool where Sage Bhrigu meditated.",
        "fitness_level": "Beginner Friendly",
        "start_point": "Gulaba / Manali, Himachal Pradesh",
        "itinerary": [
            {"day": 1, "title": "Drive Manali to Gulaba & Trek to Rola Kholi", "campsite": "Rola Kholi Campsite", "altitude": "12,500 ft (3,810 m)", "desc": "Scenic drive on Rohtang Highway and trek through pine forest up into meadows."},
            {"day": 2, "title": "Summit Day: Rola Kholi to Bhrigu Lake & Back", "campsite": "Rola Kholi Campsite", "altitude": "14,100 ft (4,298 m) Lake / 12,500 ft Camp", "desc": "Climb over snow and boulder fields to the sacred turquoise waters of Bhrigu Lake."},
            {"day": 3, "title": "Trek Rola Kholi to Pandu Ropa", "campsite": "Pandu Ropa Meadow Camp", "altitude": "10,900 ft (3,322 m)", "desc": "Descent through scenic wildflower ridges with views of Solang valley."},
            {"day": 4, "title": "Trek Pandu Ropa to Vashisht & Drive to Manali", "campsite": "Manali Hotel", "altitude": "6,725 ft (2,050 m)", "desc": "Descend into ancient Vashisht hot water spring village and conclude in Manali."}
        ]
    },
    {
        "id": "manaslu-circuit",
        "name": "Manaslu Circuit Trek",
        "tagline": "The Untouched Mountain Wilderness Circuit of Nepal",
        "region": "Nepal Himalayas",
        "country": "Nepal",
        "duration_days": 14,
        "duration_text": "14 Days / 13 Nights",
        "distance_km": 177,
        "distance_text": "177 km",
        "max_altitude_ft": 16752,
        "max_altitude_text": "16,752 ft (5,106 m)",
        "difficulty": "Difficult",
        "difficulty_slug": "difficult",
        "best_months": ["March", "April", "May", "September", "October", "November"],
        "best_season": "Spring & Autumn",
        "rating": 5.0,
        "reviews_count": 390,
        "price": "₹78,000",
        "image": "/static/img/winter_summit_trek.jpg",
        "badge": "Off-Beat Wilderness",
        "highlights": ["Circling Mt. Manaslu (8,163m)", "Larkya La Pass Crossover (5,106m)", "Ancient Tibetan Buddhist Monasteries", "Birendra Glacial Lake & Pungyen Gompa"],
        "description": "A remote alternative to the crowded Annapurna Circuit, the Manaslu Circuit circles the world's 8th highest peak through dramatic river gorges, remote Tibetan settlements, and across the snow-capped Larkya La Pass.",
        "fitness_level": "High Endurance Required",
        "start_point": "Soti Khola / Machha Khola, Nepal",
        "itinerary": [
            {"day": 1, "title": "Drive Kathmandu to Machha Khola", "campsite": "Machha Khola Teahouse", "altitude": "3,050 ft (930 m)", "desc": "Scenic mountain highway and 4x4 drive along the Budhi Gandaki river."},
            {"day": 2, "title": "Trek Machha Khola to Jagat", "campsite": "Jagat Stone Village", "altitude": "4,625 ft (1,410 m)", "desc": "Follow canyon cliff paths and cross suspension bridges over roaring rapids."},
            {"day": 3, "title": "Trek Jagat to Deng", "campsite": "Deng Teahouse", "altitude": "5,918 ft (1,804 m)", "desc": "Enter the Manaslu Conservation Area with lush bamboo and rhododendron slopes."},
            {"day": 4, "title": "Trek Deng to Namrung", "campsite": "Namrung Village", "altitude": "8,628 ft (2,630 m)", "desc": "First views of Mt. Manaslu and traditional Tibetan Mani walls."},
            {"day": 5, "title": "Trek Namrung to Samagaon", "campsite": "Samagaon Heritage Teahouse", "altitude": "11,581 ft (3,530 m)", "desc": "Wide open glacial valley with the huge mass of Manaslu dominating the skyline."},
            {"day": 6, "title": "Acclimatization Day at Samagaon: Excursion to Pungyen Gompa", "campsite": "Samagaon Teahouse", "altitude": "13,200 ft (4,023 m)", "desc": "Hike to Pungyen Gompa and the glacial snout of Manaslu glacier."},
            {"day": 7, "title": "Trek Samagaon to Samdo", "campsite": "Samdo Tibetan Camp", "altitude": "12,664 ft (3,860 m)", "desc": "High yak pasture trail close to the Tibetan border."},
            {"day": 8, "title": "Trek Samdo to Dharamsala (Larkya Phedi)", "campsite": "Dharamsala High Lodge", "altitude": "14,632 ft (4,460 m)", "desc": "Base camp beneath the Larkya Glacier."},
            {"day": 9, "title": "Summit Day: Cross Larkya La Pass & Descend to Bimthang", "campsite": "Bimthang Valley Lodge", "altitude": "16,752 ft (5,106 m) Pass / 12,139 ft Camp", "desc": "Magnificent crossing of Larkya La with views of Himlung Himal, Cheo Himal, and Annapurna II."},
            {"day": 10, "title": "Trek Bimthang to Tilije", "campsite": "Tilije Village Lodge", "altitude": "7,545 ft (2,300 m)", "desc": "Descend through pine and rhododendron forests along Dudh Khola."},
            {"day": 11, "title": "Trek Tilije to Dharapani & Drive to Besisahar", "campsite": "Besisahar Hotel", "altitude": "2,493 ft (760 m)", "desc": "Join the Annapurna circuit trail and drive to Besisahar."},
            {"day": 12, "title": "Drive Besisahar back to Kathmandu", "campsite": "Kathmandu Hotel", "altitude": "4,593 ft (1,400 m)", "desc": "Celebration evening in Thamel, Kathmandu."}
        ]
    },
    {
        "id": "inca-trail",
        "name": "Classic Inca Trail to Machu Picchu",
        "tagline": "The Ancient Stone Highway of the Incan Empire",
        "region": "Andes Mountain Range",
        "country": "Peru",
        "duration_days": 4,
        "duration_text": "4 Days / 3 Nights",
        "distance_km": 42,
        "distance_text": "42 km",
        "max_altitude_ft": 13828,
        "max_altitude_text": "13,828 ft (4,215 m)",
        "difficulty": "Moderate",
        "difficulty_slug": "moderate",
        "best_months": ["May", "June", "July", "August", "September"],
        "best_season": "Dry Andean Season",
        "rating": 5.0,
        "reviews_count": 1420,
        "price": "₹62,000",
        "image": "/static/img/trekking_mountain.jpg",
        "badge": "World Wonder",
        "highlights": ["Sun Gate Entrance to Machu Picchu", "Dead Woman's Pass (4,215m)", "Wiñay Wayna Cloud Forest Ruins", "Original hand-laid Inca stone steps"],
        "description": "The world's most famous pilgrimage trail traverses misty cloud forests, high Andean passes, and cliff-hanging Incan archaeological ruins, culminating in a grand sunrise view of Machu Picchu from Inti Punku.",
        "fitness_level": "Moderate Fitness",
        "start_point": "Km 82, Sacred Valley, Cusco, Peru",
        "itinerary": [
            {"day": 1, "title": "Cusco to Km 82 & Trek to Wayllabamba", "campsite": "Wayllabamba Camp", "altitude": "9,842 ft (3,000 m)", "desc": "Begin trail along the Urubamba river, exploring Patallacta ruins."},
            {"day": 2, "title": "Trek Wayllabamba to Pacaymayo via Dead Woman's Pass", "campsite": "Pacaymayo Campsite", "altitude": "13,828 ft (4,215 m) Pass / 11,800 ft Camp", "desc": "Challenging stone-stair ascent through Polylepis dwarf forests over Dead Woman's Pass."},
            {"day": 3, "title": "Trek Pacaymayo to Wiñay Wayna", "campsite": "Wiñay Wayna Cloud Forest Camp", "altitude": "8,858 ft (2,700 m)", "desc": "Explore Runkurakay, Sayacmarca, and the terraced hanging city of Wiñay Wayna."},
            {"day": 4, "title": "Sun Gate (Inti Punku) to Machu Picchu Citadel & Return Cusco", "campsite": "Cusco Hotel", "altitude": "7,972 ft (2,430 m) Machu Picchu", "desc": "Enter Machu Picchu at dawn through the Sun Gate, guided exploration of the citadel, and train return to Cusco."}
        ]
    },
    {
        "id": "mount-kilimanjaro",
        "name": "Mount Kilimanjaro (Machame Route)",
        "tagline": "Standing on the Roof of the African Continent",
        "region": "Kilimanjaro",
        "country": "Tanzania",
        "duration_days": 7,
        "duration_text": "7 Days / 6 Nights",
        "distance_km": 62,
        "distance_text": "62 km",
        "max_altitude_ft": 19341,
        "max_altitude_text": "19,341 ft (5,895 m)",
        "difficulty": "Difficult",
        "difficulty_slug": "difficult",
        "best_months": ["January", "February", "June", "July", "August", "September", "October"],
        "best_season": "Dry Season",
        "rating": 5.0,
        "reviews_count": 980,
        "price": "₹1,45,000",
        "image": "/static/img/winter_summit_trek.jpg",
        "badge": "Seven Summits",
        "highlights": ["Uhuru Peak (5,895m) - Highest Point in Africa", "5 Distinct Ecological Climate Zones", "Famous Barranco Wall Scramble", "Lava Tower (4,630m) Acclimatization"],
        "description": "Mount Kilimanjaro is the tallest free-standing volcanic mountain in the world. The scenic Machame Route ('Whiskey Route') climbs through rainforest, moorland, alpine desert, and arctic summit glaciers.",
        "fitness_level": "High Endurance Required",
        "start_point": "Machame Gate, Moshi, Tanzania",
        "itinerary": [
            {"day": 1, "title": "Machame Gate to Machame Camp", "campsite": "Machame Rainforest Camp", "altitude": "9,300 ft (2,835 m)", "desc": "Hike through lush montane rainforest with giant ferns and colobus monkeys."},
            {"day": 2, "title": "Trek Machame Camp to Shira Cave", "campsite": "Shira Cave Camp", "altitude": "12,300 ft (3,750 m)", "desc": "Emerge from forest into vast heath and moorland over the Shira Plateau."},
            {"day": 3, "title": "Trek to Lava Tower & Descend to Barranco Camp", "campsite": "Barranco Campsite", "altitude": "15,190 ft (4,630 m) Tower / 12,960 ft Camp", "desc": "Climb high to Lava Tower and sleep low in the shadow of the great Barranco Wall for optimal acclimatization."},
            {"day": 4, "title": "Scramble Barranco Wall & Trek to Karanga Camp", "campsite": "Karanga High Valley Camp", "altitude": "13,100 ft (3,995 m)", "desc": "Fun non-technical scramble up the sheer Barranco Wall with epic valley views."},
            {"day": 5, "title": "Trek Karanga to Barafu Summit Base Camp", "campsite": "Barafu Base Camp", "altitude": "15,331 ft (4,673 m)", "desc": "Traverse the barren alpine desert landscape to the windswept summit ridge base."},
            {"day": 6, "title": "Summit Night: Barafu to Uhuru Peak & Descend to Mweka", "campsite": "Mweka Camp", "altitude": "19,341 ft (5,895 m) Summit / 10,065 ft Camp", "desc": "Midnight summit push past Stella Point to reach Uhuru Peak at sunrise; celebrate on the roof of Africa!"},
            {"day": 7, "title": "Mweka Camp to Mweka Gate & Return Moshi", "campsite": "Moshi Hotel", "altitude": "5,380 ft (1,640 m)", "desc": "Descend to gate, receive summit certificates, and celebrate."}
        ]
    },
    {
        "id": "friendship-peak",
        "name": "Friendship Peak Expedition",
        "tagline": "The Premier Open Mountaineering Summit of Pir Panjal",
        "region": "Himachal Pradesh",
        "country": "India",
        "duration_days": 8,
        "duration_text": "8 Days / 7 Nights",
        "distance_km": 34,
        "distance_text": "34 km",
        "max_altitude_ft": 17346,
        "max_altitude_text": "17,346 ft (5,289 m)",
        "difficulty": "Expert",
        "difficulty_slug": "expert",
        "best_months": ["May", "June", "September", "October"],
        "best_season": "Summer & Autumn",
        "rating": 4.9,
        "reviews_count": 340,
        "price": "₹29,500",
        "image": "/static/img/mountain_hero.jpg",
        "badge": "Trekking Peak",
        "highlights": ["17,346 ft Summit Push", "Crampon & Ice Axe Training", "Panoramic Views of Hanuman Tibba (5,982m)", "Lady Leg Ridge Campsite"],
        "description": "Friendship Peak is India's most sought-after non-technical mountaineering summit. Rising dramatically in the Pir Panjal range overlooking Solang Valley, it serves as the ultimate stepping stone from high-altitude trekking into true mountaineering.",
        "fitness_level": "High Endurance & Technical Prep",
        "start_point": "Solang Nallah, Manali, Himachal Pradesh",
        "itinerary": [
            {"day": 1, "title": "Drive Manali to Solang & Trek to Dhundi", "campsite": "Dhundi Riverside Camp", "altitude": "9,300 ft (2,835 m)", "desc": "Trek alongside Beas River through lush pine and birch woodlands to Dhundi."},
            {"day": 2, "title": "Trek Dhundi to Bakarthach", "campsite": "Bakarthach Meadow Camp", "altitude": "10,800 ft (3,292 m)", "desc": "Climb above tree line onto the alpine shepherd meadows of Bakarthach."},
            {"day": 3, "title": "Trek Bakarthach to Lady Leg (Advanced Base Camp)", "campsite": "Lady Leg High Camp", "altitude": "12,800 ft (3,901 m)", "desc": "Steep ascent over grassy moraine ridges to the prominent high camp named Lady Leg."},
            {"day": 4, "title": "Acclimatization & Snow Craft Training Day", "campsite": "Lady Leg High Camp", "altitude": "12,800 ft (3,901 m)", "desc": "Hands-on training session on using crampons, ice axes, self-arrest, and roping up."},
            {"day": 5, "title": "Climb Lady Leg to Summit Camp", "campsite": "Summit High Camp", "altitude": "14,800 ft (4,511 m)", "desc": "Move gear up through glacier scree to the windswept summit high camp."},
            {"day": 6, "title": "Summit Night: Summit Push to 17,346 ft & Return to Bakarthach", "campsite": "Bakarthach Camp", "altitude": "17,346 ft (5,289 m) Summit / 10,800 ft Camp", "desc": "Midnight summit push up the steep snow shoulder; stand on top for sunrise over Hanuman Tibba, Shitidhar, and Indrasan."},
            {"day": 7, "title": "Buffer / Weather Day or Trek to Dhundi", "campsite": "Dhundi Camp", "altitude": "9,300 ft (2,835 m)", "desc": "Contingency day for weather or celebratory descent back to Dhundi."},
            {"day": 8, "title": "Trek Dhundi to Solang & Drive to Manali", "campsite": "Manali Hotel", "altitude": "6,725 ft (2,050 m)", "desc": "Complete the expedition and celebrate summit success in Old Manali."}
        ]
    },
    {
        "id": "yunam-peak",
        "name": "Yunam Peak Expedition",
        "tagline": "The 6,000-Meter High-Altitude Gateway Peak of Lahaul",
        "region": "Himachal Pradesh",
        "country": "India",
        "duration_days": 8,
        "duration_text": "8 Days / 7 Nights",
        "distance_km": 30,
        "distance_text": "30 km",
        "max_altitude_ft": 20111,
        "max_altitude_text": "20,111 ft (6,130 m)",
        "difficulty": "Expert",
        "difficulty_slug": "expert",
        "best_months": ["July", "August", "September"],
        "best_season": "Lahaul Summer",
        "rating": 5.0,
        "reviews_count": 220,
        "price": "₹34,000",
        "image": "/static/img/winter_summit_trek.jpg",
        "badge": "6,000m Summit",
        "highlights": ["Breaching the 20,000 ft (6,130m) Milestone", "Baralacha La Pass & Suraj Tal Lake", "Panoramic views of Chandra Bhaga (CB) range", "Non-technical scree & snow summit"],
        "description": "Standing proudly at 6,130m near the legendary Baralacha La pass, Yunam Peak is one of India's few accessible 6,000-meter peaks that does not require technical mountaineering gear while testing extreme high-altitude endurance.",
        "fitness_level": "Exceptional Stamina & Altitude Acclimatization",
        "start_point": "Manali / Keylong, Himachal Pradesh",
        "itinerary": [
            {"day": 1, "title": "Drive Manali to Jispa via Atal Tunnel", "campsite": "Jispa Riverside Lodge", "altitude": "10,500 ft (3,200 m)", "desc": "Drive through the Atal Tunnel into Lahaul valley along the Bhaga River."},
            {"day": 2, "title": "Acclimatization Walk in Jispa", "campsite": "Jispa Lodge", "altitude": "10,500 ft (3,200 m)", "desc": "Hike to nearby monasteries and mountain slopes to adapt to higher altitude."},
            {"day": 3, "title": "Drive Jispa to Bharatpur (Base Camp)", "campsite": "Bharatpur Base Camp", "altitude": "14,800 ft (4,511 m)", "desc": "Drive past the shimmering turquoise waters of Suraj Tal over Baralacha La pass to Bharatpur."},
            {"day": 4, "title": "Acclimatization & Load Ferry to Advanced Base Camp (ABC)", "campsite": "Bharatpur Base Camp", "altitude": "16,800 ft (5,120 m) Walk / 14,800 ft Camp", "desc": "Climb high with gear to ABC on moraine ridge and descend to sleep low."},
            {"day": 5, "title": "Move to Advanced Base Camp (ABC)", "campsite": "Yunam ABC", "altitude": "16,800 ft (5,120 m)", "desc": "Establish high camp near the snowline with stunning sunset views of cold desert peaks."},
            {"day": 6, "title": "Summit Night: ABC to Yunam Peak Summit (6,130m) & Return to Base Camp", "campsite": "Bharatpur Base Camp", "altitude": "20,111 ft (6,130 m) Summit / 14,800 ft Camp", "desc": "Pre-dawn 3 AM push up the steep scree and snow slopes to breach 6,130m with 360° views across Zanskar and Lahaul."},
            {"day": 7, "title": "Buffer / Contingency Weather Day", "campsite": "Bharatpur Camp", "altitude": "14,800 ft (4,511 m)", "desc": "Reserved for bad weather or additional summit attempt."},
            {"day": 8, "title": "Drive Bharatpur to Manali", "campsite": "Manali Hotel", "altitude": "6,725 ft (2,050 m)", "desc": "Scenic drive back over passes to conclude the successful 6,000m expedition."}
        ]
    },
    {
        "id": "kang-yatse-1",
        "name": "Kang Yatse I Expedition",
        "tagline": "The Technical 6,400m Throne Peak of Markha Valley",
        "region": "Ladakh",
        "country": "India",
        "duration_days": 11,
        "duration_text": "11 Days / 10 Nights",
        "distance_km": 72,
        "distance_text": "72 km",
        "max_altitude_ft": 21000,
        "max_altitude_text": "21,000 ft (6,400 m)",
        "difficulty": "Expert",
        "difficulty_slug": "expert",
        "best_months": ["July", "August", "September"],
        "best_season": "Ladakh Summer",
        "rating": 5.0,
        "reviews_count": 180,
        "price": "₹58,000",
        "image": "/static/img/mountain_hero.jpg",
        "badge": "Technical 6,400m",
        "highlights": ["21,000 ft (6,400m) Technical Summit", "Knife-Edge Snow Arete & Fixed Rope Ascent", "Sprawling Nimaling Alpine Plateau", "K2 & Karakoram Far Horizon Views"],
        "description": "Kang Yatse I is the true crowning jewel of the Markha Valley. Unlike its trekking counterpart KY-II, Kang Yatse I requires technical snow and ice craft, fixed-rope climbing along a razor-sharp summit knife-edge ridge above 20,000 ft.",
        "fitness_level": "Mountaineering Technical Training Required",
        "start_point": "Leh, Ladakh",
        "itinerary": [
            {"day": 1, "title": "Acclimatization in Leh", "campsite": "Leh Hotel", "altitude": "11,500 ft (3,505 m)", "desc": "Rest day and hydration walk in Leh town."},
            {"day": 2, "title": "Drive Leh to Chilling & Trek to Skiu", "campsite": "Skiu Village Camp", "altitude": "11,150 ft (3,398 m)", "desc": "Enter the red granite gorges of Markha Valley."},
            {"day": 3, "title": "Trek Skiu to Markha", "campsite": "Markha Village Camp", "altitude": "12,460 ft (3,798 m)", "desc": "Hike past Tibetan chortens and willow groves to Markha village."},
            {"day": 4, "title": "Trek Markha to Thachungtse", "campsite": "Thachungtse Camp", "altitude": "13,940 ft (4,249 m)", "desc": "Climb towards the foot of the twin Kang Yatse massifs."},
            {"day": 5, "title": "Trek Thachungtse to Nimaling High Plateau", "campsite": "Nimaling High Camp", "altitude": "15,580 ft (4,749 m)", "desc": "Reach the expansive pastures where Ladakhi nomads graze pashmina goats."},
            {"day": 6, "title": "Trek Nimaling to Kang Yatse Base Camp", "campsite": "KY Base Camp", "altitude": "16,730 ft (5,100 m)", "desc": "Establish base camp right beneath the hanging glaciers of Kang Yatse."},
            {"day": 7, "title": "Load Ferry & Technical Training to High Camp (ABC)", "campsite": "KY Base Camp", "altitude": "18,200 ft (5,547 m) / 16,730 ft Camp", "desc": "Fix lines, practice jumaring and front-pointing on ice."},
            {"day": 8, "title": "Move to Summit High Camp (ABC)", "campsite": "KY High Camp", "altitude": "18,200 ft (5,547 m)", "desc": "Position team on the high ridge for the technical push."},
            {"day": 9, "title": "Summit Day: High Camp to Kang Yatse I (6,400m) & Return to Base Camp", "campsite": "KY Base Camp", "altitude": "21,000 ft (6,400 m) Summit / 16,730 ft Camp", "desc": "11 PM midnight alpine departure; negotiate the crevasse fields, scale the steep headwall, and traverse the exposed knife-edge arete to the 6,400m summit."},
            {"day": 10, "title": "Trek Base Camp over Kongmaru La (5,200m) to Chokdo & Drive Leh", "campsite": "Leh Hotel", "altitude": "17,060 ft (5,200 m) Pass / 11,500 ft Leh", "desc": "Cross the high pass with views of the Tibetan plateau and return to Leh."},
            {"day": 11, "title": "Depart from Leh", "campsite": "Leh Airport", "altitude": "10,682 ft (3,256 m)", "desc": "Depart with memories of conquering one of India's greatest technical peaks."}
        ]
    },
    {
        "id": "kang-yatse-2",
        "name": "Kang Yatse II Expedition",
        "tagline": "The Premier 6,250m Trekking Peak of Ladakh",
        "region": "Ladakh",
        "country": "India",
        "duration_days": 10,
        "duration_text": "10 Days / 9 Nights",
        "distance_km": 68,
        "distance_text": "68 km",
        "max_altitude_ft": 20505,
        "max_altitude_text": "20,505 ft (6,250 m)",
        "difficulty": "Expert",
        "difficulty_slug": "expert",
        "best_months": ["July", "August", "September"],
        "best_season": "Ladakh Summer",
        "rating": 4.9,
        "reviews_count": 310,
        "price": "₹45,000",
        "image": "/static/img/trekking_mountain.jpg",
        "badge": "6,250m Trekking Peak",
        "highlights": ["Standing at 20,505 ft (6,250m)", "Approach through famous Markha Valley", "Panoramic Nimaling High Plateau", "Zanskar & Karakoram Mountain Views"],
        "description": "Kang Yatse II is the ultimate peak for trekkers aspiring to break the magical 20,000 ft altitude barrier. Accessible via the world-famous Markha Valley trek, KY-II delivers an exhilarating non-technical snow climb with panoramic views across Ladakh, Tibet, and the Karakoram.",
        "fitness_level": "High Endurance & Snow Gear Training",
        "start_point": "Leh, Ladakh",
        "itinerary": [
            {"day": 1, "title": "Acclimatization in Leh", "campsite": "Leh Hotel", "altitude": "11,500 ft (3,505 m)", "desc": "Rest day in Leh to acclimatize to high altitude."},
            {"day": 2, "title": "Drive Leh to Chilling & Trek to Skiu", "campsite": "Skiu Camp", "altitude": "11,150 ft (3,398 m)", "desc": "Cross Zanskar river and trek along the river canyon."},
            {"day": 3, "title": "Trek Skiu to Markha Village", "campsite": "Markha Village Camp", "altitude": "12,460 ft (3,798 m)", "desc": "Walk past ancient Buddhist monasteries and green barley fields."},
            {"day": 4, "title": "Trek Markha to Thachungtse", "campsite": "Thachungtse Camp", "altitude": "13,940 ft (4,249 m)", "desc": "Approach the alpine high valleys beneath Kang Yatse."},
            {"day": 5, "title": "Trek Thachungtse to Nimaling Plateau", "campsite": "Nimaling Camp", "altitude": "15,580 ft (4,749 m)", "desc": "Ascend to the vast grazing pastures beneath the peak."},
            {"day": 6, "title": "Trek Nimaling to Kang Yatse Base Camp", "campsite": "KY Base Camp", "altitude": "16,730 ft (5,100 m)", "desc": "Climb up to base camp and prepare crampons and harness."},
            {"day": 7, "title": "Acclimatization & Snow Training Day", "campsite": "KY Base Camp", "altitude": "16,730 ft (5,100 m)", "desc": "Rest and rope-up training on nearby snow slopes."},
            {"day": 8, "title": "Summit Night: Base Camp to Kang Yatse II (6,250m) & Return", "campsite": "KY Base Camp", "altitude": "20,505 ft (6,250 m) Summit / 16,730 ft Camp", "desc": "Midnight summit climb up the snow slope to reach the 6,250m top at sunrise with breathtaking 360° panoramas."},
            {"day": 9, "title": "Trek Base Camp over Kongmaru La (5,200m) to Chokdo & Drive Leh", "campsite": "Leh Hotel", "altitude": "17,060 ft (5,200 m) Pass / 11,500 ft Leh", "desc": "Cross the high pass and drive back to Leh for celebrations."},
            {"day": 10, "title": "Depart Leh Airport", "campsite": "Leh Airport", "altitude": "10,682 ft (3,256 m)", "desc": "Fly back over the Himalayas with a 6,250m summit under your belt."}
        ]
    },
    {
        "id": "stok-kangri",
        "name": "Stok Kangri Summit",
        "tagline": "The Legendary 20,000 ft Summit of Ladakh",
        "region": "Ladakh",
        "country": "India",
        "duration_days": 8,
        "duration_text": "8 Days / 7 Nights",
        "distance_km": 40,
        "distance_text": "40 km",
        "max_altitude_ft": 20187,
        "max_altitude_text": "20,187 ft (6,153 m)",
        "difficulty": "Expert",
        "difficulty_slug": "expert",
        "best_months": ["July", "August", "September"],
        "best_season": "Ladakh Summer",
        "rating": 5.0,
        "reviews_count": 520,
        "price": "₹42,000",
        "image": "/static/img/winter_summit_trek.jpg",
        "badge": "20,000 ft Legend",
        "highlights": ["20,187 ft (6,153m) Summit Ridge", "Glacier Crossing & Knife-Edge Snow Shoulder", "Views of K2 and Karakoram Ranges", "Historic Stok Palace Approach"],
        "description": "Stok Kangri is the undisputed king of Indian trekking peaks. Towering directly over Leh at 6,153m, its knife-edge summit ridge grants unparalleled views of the Karakoram range, K2 on clear days, and the Indus valley thousands of feet below.",
        "fitness_level": "Exceptional Mountaineering Stamina",
        "start_point": "Stok Village, Leh, Ladakh",
        "itinerary": [
            {"day": 1, "title": "Acclimatization in Leh", "campsite": "Leh Hotel", "altitude": "11,500 ft (3,505 m)", "desc": "Rest day in Leh for acclimatization."},
            {"day": 2, "title": "Drive Leh to Stok Village & Trek to Chang Ma", "campsite": "Chang Ma Campsite", "altitude": "13,080 ft (3,987 m)", "desc": "Begin trek from the historic royal Stok Palace into deep mountain gorges."},
            {"day": 3, "title": "Trek Chang Ma to Mankorma", "campsite": "Mankorma Campsite", "altitude": "14,200 ft (4,328 m)", "desc": "Gentle climb along the stream with first views of Stok Kangri's icy face."},
            {"day": 4, "title": "Trek Mankorma to Stok Kangri Base Camp", "campsite": "Stok Base Camp", "altitude": "16,300 ft (4,968 m)", "desc": "Ascend onto high moraine plateau where base camp is situated."},
            {"day": 5, "title": "Acclimatization & Glacier Training Day", "campsite": "Stok Base Camp", "altitude": "16,300 ft (4,968 m)", "desc": "Practice crampon footwork and roped glacier crossing."},
            {"day": 6, "title": "Summit Night: Base Camp to Stok Kangri Summit (6,153m) & Back", "campsite": "Stok Base Camp", "altitude": "20,187 ft (6,153 m) Summit / 16,300 ft Camp", "desc": "11 PM midnight summit push across the glacier, up the steep headwall to the famous knife-edge ridge; summit at sunrise with views of K2."},
            {"day": 7, "title": "Buffer / Contingency Weather Day", "campsite": "Stok Base Camp", "altitude": "16,300 ft (4,968 m)", "desc": "Reserved for weather safety."},
            {"day": 8, "title": "Trek Base Camp to Stok Village & Drive to Leh", "campsite": "Leh Hotel", "altitude": "11,500 ft (3,505 m)", "desc": "Descend to Stok village and celebrate summit victory in Leh."}
        ]
    },
    {
        "id": "pangarchulla-peak",
        "name": "Pangarchulla Peak Trek",
        "tagline": "The Thrilling Chimney Climb & Snow Ridge Summit",
        "region": "Uttarakhand",
        "country": "India",
        "duration_days": 6,
        "duration_text": "6 Days / 5 Nights",
        "distance_km": 38,
        "distance_text": "38 km",
        "max_altitude_ft": 15069,
        "max_altitude_text": "15,069 ft (4,593 m)",
        "difficulty": "Difficult",
        "difficulty_slug": "difficult",
        "best_months": ["March", "April", "May", "October", "November"],
        "best_season": "Spring Snow & Autumn",
        "rating": 4.9,
        "reviews_count": 410,
        "price": "₹11,500",
        "image": "/static/img/mountain_hero.jpg",
        "badge": "Spring Snow Summit",
        "highlights": ["15,069 ft (4,593m) Sharp Peak Summit", "Front-Row Grand Views of Mt. Nanda Devi", "Thrilling Boulder & Snow Ridge Scramble", "Gorson Bugyal & Rhododendron Forests"],
        "description": "Pangarchulla Peak is one of Garhwal's most dramatic peak climbs. Rising from the Kuari Pass trail, it involves ascending vast snow gullies, scaling boulder chimneys, and conquering a knife-edge ridge facing Mt. Nanda Devi, Chaukhamba, and Dronagiri.",
        "fitness_level": "High Endurance Required",
        "start_point": "Joshimath, Uttarakhand",
        "itinerary": [
            {"day": 1, "title": "Drive Rishikesh to Joshimath", "campsite": "Joshimath Hotel", "altitude": "6,150 ft (1,875 m)", "desc": "Mountain drive along holy river confluences."},
            {"day": 2, "title": "Drive Joshimath to Dhak & Trek to Gulling Top", "campsite": "Gulling Top Camp", "altitude": "9,600 ft (2,926 m)", "desc": "Trek through pine woods and terrace farms."},
            {"day": 3, "title": "Trek Gulling Top to Khullara Campsite", "campsite": "Khullara Meadow Camp", "altitude": "11,100 ft (3,383 m)", "desc": "Ascend into dense rhododendron woods opening into Khullara meadow."},
            {"day": 4, "title": "Summit Day: Khullara to Pangarchulla Peak (15,069 ft) & Back", "campsite": "Khullara Camp", "altitude": "15,069 ft (4,593 m) Summit / 11,100 ft Camp", "desc": "3 AM pre-dawn summit push over steep snowfields and razor-edge rock ridge to stand atop Pangarchulla facing Nanda Devi."},
            {"day": 5, "title": "Trek Khullara to Auli via Gorson Bugyal & Drive to Joshimath", "campsite": "Joshimath Hotel", "altitude": "6,150 ft (1,875 m)", "desc": "Traverse the vast golden meadows of Gorson Bugyal down to Auli."},
            {"day": 6, "title": "Drive Joshimath to Rishikesh", "campsite": "Rishikesh Terminal", "altitude": "1,120 ft (340 m)", "desc": "Return drive to Rishikesh by late evening."}
        ]
    },
    {
        "id": "mera-peak",
        "name": "Mera Peak Expedition",
        "tagline": "The Highest Trekking Peak in Nepal with 5 Eight-Thousander Views",
        "region": "Nepal Himalayas",
        "country": "Nepal",
        "duration_days": 18,
        "duration_text": "18 Days / 17 Nights",
        "distance_km": 125,
        "distance_text": "125 km",
        "max_altitude_ft": 21247,
        "max_altitude_text": "21,247 ft (6,476 m)",
        "difficulty": "Expert",
        "difficulty_slug": "expert",
        "best_months": ["April", "May", "September", "October", "November"],
        "best_season": "Spring & Autumn",
        "rating": 5.0,
        "reviews_count": 290,
        "price": "₹1,25,000",
        "image": "/static/img/winter_summit_trek.jpg",
        "badge": "Highest Nepal Trekking Peak",
        "highlights": ["6,476m (21,247 ft) Summit", "Unrivaled view of 5 Eight-Thousanders (Everest, Lhotse, Cho Oyu, Makalu, Kanchenjunga)", "Pristine Hinku Valley Wilderness", "Glacier High Camp (5,800m)"],
        "description": "Mera Peak (6,476m) holds the distinction of being Nepal's highest permitted trekking peak. Its summit provides the most panoramic vantage point in the world, with direct views of five of the earth's six highest mountains.",
        "fitness_level": "Mountaineering Expedition Stamina",
        "start_point": "Lukla, Nepal",
        "itinerary": [
            {"day": 1, "title": "Fly Kathmandu to Lukla & Trek to Paiya", "campsite": "Paiya Teahouse", "altitude": "8,956 ft (2,730 m)", "desc": "Scenic mountain flight into Lukla and trek south into quiet valleys."},
            {"day": 2, "title": "Trek Paiya to Panggom", "campsite": "Panggom Lodge", "altitude": "9,348 ft (2,849 m)", "desc": "Hike over Panggom La through rhododendron and bamboo forests."},
            {"day": 3, "title": "Trek Panggom to Ningsow", "campsite": "Ningsow Lodge", "altitude": "9,397 ft (2,864 m)", "desc": "Follow high ridges with views of the Dudh Koshi valley."},
            {"day": 4, "title": "Trek Ningsow to Chhatra Khola", "campsite": "Chhatra Khola Lodge", "altitude": "9,184 ft (2,799 m)", "desc": "Enter the remote Hinku River gorge."},
            {"day": 5, "title": "Trek Chhatra Khola to Kothe", "campsite": "Kothe Teahouse", "altitude": "11,811 ft (3,600 m)", "desc": "Join the main Hinku valley trail beneath towering cliffs."},
            {"day": 6, "title": "Trek Kothe to Thaknak", "campsite": "Thaknak Teahouse", "altitude": "14,295 ft (4,357 m)", "desc": "Walk alongside the glacial moraine with views of Mera North."},
            {"day": 7, "title": "Trek Thaknak to Khare (Base Camp)", "campsite": "Khare Mountain Lodge", "altitude": "16,404 ft (5,000 m)", "desc": "Reach the base village beneath the vast Mera Glacier."},
            {"day": 8, "title": "Acclimatization & Glacier Training in Khare", "campsite": "Khare Lodge", "altitude": "16,404 ft (5,000 m)", "desc": "Practice ascending fixed ropes and crampon techniques."},
            {"day": 9, "title": "Climb Khare to Mera High Camp", "campsite": "Mera High Camp", "altitude": "19,028 ft (5,800 m)", "desc": "Cross the Mera La glacier to establish high camp perched on a rock shelf."},
            {"day": 10, "title": "Summit Night: High Camp to Mera Peak Summit (6,476m) & Return Khare", "campsite": "Khare Lodge", "altitude": "21,247 ft (6,476 m) Summit / 16,404 ft Camp", "desc": "2 AM summit push up the gentle glacier to the summit dome for the greatest mountain vista on planet Earth."},
            {"day": 11, "title": "Buffer / Weather Contingency Day", "campsite": "Khare Lodge", "altitude": "16,404 ft (5,000 m)", "desc": "Contingency day for summit safety."},
            {"day": 12, "title": "Trek Khare to Kothe", "campsite": "Kothe Teahouse", "altitude": "11,811 ft (3,600 m)", "desc": "Descend rapidly down the Hinku valley."},
            {"day": 13, "title": "Trek Kothe to Thuli Kharka", "campsite": "Thuli Kharka Camp", "altitude": "14,107 ft (4,300 m)", "desc": "Climb up towards Zatrwa La pass."},
            {"day": 14, "title": "Cross Zatrwa La (4,600m) & Descend to Lukla", "campsite": "Lukla Hotel", "altitude": "9,383 ft (2,860 m)", "desc": "Cross the high pass back into Lukla and celebrate summit triumph."},
            {"day": 15, "title": "Fly Lukla to Kathmandu", "campsite": "Kathmandu Hotel", "altitude": "4,593 ft (1,400 m)", "desc": "Return flight to Kathmandu for celebration dinner."}
        ]
    },
    {
        "id": "island-peak",
        "name": "Island Peak (Imja Tse)",
        "tagline": "The Classic Glacial Summit Facing Lhotse South Face",
        "region": "Nepal Himalayas",
        "country": "Nepal",
        "duration_days": 16,
        "duration_text": "16 Days / 15 Nights",
        "distance_km": 110,
        "distance_text": "110 km",
        "max_altitude_ft": 20305,
        "max_altitude_text": "20,305 ft (6,189 m)",
        "difficulty": "Expert",
        "difficulty_slug": "expert",
        "best_months": ["April", "May", "October", "November"],
        "best_season": "Spring & Autumn",
        "rating": 5.0,
        "reviews_count": 380,
        "price": "₹1,15,000",
        "image": "/static/img/trekking_mountain.jpg",
        "badge": "6,189m Glacial Climb",
        "highlights": ["20,305 ft (6,189m) Summit", "Climbing the steep 100m Ice Headwall with Jumars", "Front-Row View of Mt. Lhotse (8,516m) & Ama Dablam", "Combined with Everest Base Camp Trek"],
        "description": "Island Peak (Imja Tse) rises like an island in a sea of ice in the Chhukung valley. It offers the classic Himalayan climbing experience: crossing crevassed glaciers with ladders, ascending a sheer ice headwall, and walking an airy summit knife-edge ridge with the immense South Face of Lhotse towering directly overhead.",
        "fitness_level": "Technical Crampon & Jumar Skills Required",
        "start_point": "Lukla, Nepal",
        "itinerary": [
            {"day": 1, "title": "Fly Kathmandu to Lukla & Trek to Phakding", "campsite": "Phakding Teahouse", "altitude": "8,562 ft (2,610 m)", "desc": "Fly into Lukla and trek along the Dudh Koshi river."},
            {"day": 2, "title": "Trek Phakding to Namche Bazaar", "campsite": "Namche Bazaar Lodge", "altitude": "11,286 ft (3,440 m)", "desc": "Cross the famous Hillary suspension bridge to enter Sherpa capital Namche."},
            {"day": 3, "title": "Acclimatization Day in Namche", "campsite": "Namche Lodge", "altitude": "11,286 ft (3,440 m)", "desc": "Hike to Everest View Hotel for first panorama of Everest, Lhotse, and Ama Dablam."},
            {"day": 4, "title": "Trek Namche to Tengboche", "campsite": "Tengboche Monastery Lodge", "altitude": "12,694 ft (3,870 m)", "desc": "Visit the world-famous Buddhist monastery at Tengboche."},
            {"day": 5, "title": "Trek Tengboche to Dingboche", "campsite": "Dingboche Lodge", "altitude": "14,468 ft (4,410 m)", "desc": "Walk above tree line with magnificent views of Ama Dablam."},
            {"day": 6, "title": "Trek Dingboche to Chhukung", "campsite": "Chhukung Teahouse", "altitude": "15,518 ft (4,730 m)", "desc": "Head east into the Imja valley beneath the colossal south face of Lhotse."},
            {"day": 7, "title": "Trek Chhukung to Island Peak Base Camp", "campsite": "Island Peak Base Camp", "altitude": "16,732 ft (5,100 m)", "desc": "Establish camp and conduct pre-climb training with jumars and figure-of-8 descenders."},
            {"day": 8, "title": "Move to High Camp / Rest & Preparation", "campsite": "High Camp", "altitude": "18,372 ft (5,600 m)", "desc": "Ascend rocky gully to high camp for early summit launch."},
            {"day": 9, "title": "Summit Night: High Camp to Island Peak Summit (6,189m) & Return Chhukung", "campsite": "Chhukung Teahouse", "altitude": "20,305 ft (6,189 m) Summit / 15,518 ft Camp", "desc": "1 AM launch; navigate crampon point, traverse crevasse fields, scale the 100m vertical ice headwall on fixed ropes to the summit ridge."},
            {"day": 10, "title": "Trek Chhukung to Pangboche", "campsite": "Pangboche Lodge", "altitude": "13,074 ft (3,985 m)", "desc": "Descend enjoying oxygen-rich air."},
            {"day": 11, "title": "Trek Pangboche to Namche Bazaar", "campsite": "Namche Lodge", "altitude": "11,286 ft (3,440 m)", "desc": "Return to the vibrant Sherpa town."},
            {"day": 12, "title": "Trek Namche to Lukla", "campsite": "Lukla Lodge", "altitude": "9,383 ft (2,860 m)", "desc": "Final day trek and farewell party with Sherpa climbing guides."},
            {"day": 13, "title": "Fly Lukla to Kathmandu", "campsite": "Kathmandu Hotel", "altitude": "4,593 ft (1,400 m)", "desc": "Return to Kathmandu with unforgettable summit memories."}
        ]
    }
]
